"""200 питань для PyQuest — 20 на кожну з 10 локацій."""

QUESTIONS = {
    "variables": [
        {"q":"Яке значення матиме x після: x=5; x=x+3?","code":None,"a":"5","b":"3","c":"8","d":"15","ans":"c","exp":"x спочатку 5, потім +3 = 8."},
        {"q":"Який тип даних має True?","code":None,"a":"str","b":"int","c":"float","d":"bool","ans":"d","exp":"True і False — тип bool."},
        {"q":"Що виведе цей код?","code":"x = '5'\nprint(type(x))","a":"<class 'int'>","b":"<class 'float'>","c":"<class 'str'>","d":"<class 'char'>","ans":"c","exp":"Лапки роблять значення рядком str."},
        {"q":"Яка правильна назва змінної?","code":None,"a":"my variable","b":"my-var","c":"2myvar","d":"my_var2","ans":"d","exp":"Не може починатись з цифри або містити пробіл/дефіс."},
        {"q":"Що таке None?","code":None,"a":"0","b":"False","c":"Порожній рядок","d":"Відсутність значення","ans":"d","exp":"None — тип NoneType, означає відсутність значення."},
        {"q":"Що виведе print(10/3)?","code":None,"a":"3","b":"3.333...","c":"3.0","d":"Error","ans":"b","exp":"/ завжди повертає float у Python 3."},
        {"q":"Що виведе print(10//3)?","code":None,"a":"3.333...","b":"3.0","c":"3","d":"4","ans":"c","exp":"// — цілочисельне ділення."},
        {"q":"Що виведе: a,b=5,10; print(a,b)?","code":None,"a":"5 10","b":"(5,10)","c":"[5,10]","d":"Error","ans":"a","exp":"Множинне присвоєння: a=5, b=10."},
        {"q":"Що виведе print(type(3.14))?","code":None,"a":"<class 'int'>","b":"<class 'str'>","c":"<class 'float'>","d":"<class 'double'>","ans":"c","exp":"3.14 — число з плаваючою комою, тип float."},
        {"q":"Що означає ** в Python?","code":None,"a":"Множення","b":"Ділення","c":"Степінь","d":"Коментар","ans":"c","exp":"2**3 = 8 (2 у ступені 3)."},
        {"q":"Що виведе print(7%3)?","code":None,"a":"2.333","b":"2","c":"1","d":"4","ans":"c","exp":"% — остача від ділення. 7=3*2+1."},
        {"q":"Як перевірити тип змінної x?","code":None,"a":"x.type()","b":"typeof(x)","c":"type(x)","d":"x::type","ans":"c","exp":"Вбудована функція type() повертає тип об'єкта."},
        {"q":"x=5; y='5'. Чи рівні x==y?","code":None,"a":"True","b":"False","c":"Error","d":"None","ans":"b","exp":"int 5 і str '5' — різні типи, == повертає False."},
        {"q":"Що виведе print(bool(0), bool(''), bool(1))?","code":None,"a":"True True True","b":"False False True","c":"False True False","d":"0 '' 1","ans":"b","exp":"0 і '' є falsy значеннями."},
        {"q":"Яке слово не можна використовувати як змінну?","code":None,"a":"data","b":"my_list","c":"if","d":"number","ans":"c","exp":"if — зарезервоване слово Python."},
        {"q":"Що виведе: x=10; x+=5; print(x)?","code":None,"a":"10","b":"5","c":"15","d":"105","ans":"c","exp":"x+=5 це x=x+5=15."},
        {"q":"Чи можна одній змінній присвоїти різні типи?","code":None,"a":"Ні","b":"Так, Python динамічно типізований","c":"Тільки з int()","d":"Тільки числові","ans":"b","exp":"Python — динамічно типізована мова."},
        {"q":"Що виведе print(10==10.0)?","code":None,"a":"False","b":"TypeError","c":"True","d":"None","ans":"c","exp":"== порівнює значення: 10 і 10.0 рівні."},
        {"q":"Результат int('42')?","code":None,"a":"'42'","b":"42","c":"42.0","d":"Error","ans":"b","exp":"int() конвертує рядок у ціле число."},
        {"q":"Що виведе print(2**10)?","code":None,"a":"20","b":"1024","c":"210","d":"Error","ans":"b","exp":"2 у степені 10 = 1024."},
    ],

    "conditions": [
        {"q":"Що виведе цей код?","code":"x=10\nif x>5:\n    print('Більше')\nelse:\n    print('Менше')","a":"Менше","b":"Більше","c":"Нічого","d":"Error","ans":"b","exp":"10>5 є True — виконується if."},
        {"q":"Що виведе?","code":"x=5\nif x>10:\n    print('A')\nelif x>3:\n    print('B')\nelse:\n    print('C')","a":"A","b":"B","c":"C","d":"B і C","ans":"b","exp":"x>10 False; x>3 True → elif."},
        {"q":"and повертає True коли?","code":None,"a":"Хоч одна умова True","b":"Обидві умови True","c":"Жодна не True","d":"Завжди","ans":"b","exp":"and — обидва операнди мають бути True."},
        {"q":"print(5>3 and 2<4)?","code":None,"a":"False","b":"Error","c":"5>3","d":"True","ans":"d","exp":"True and True = True."},
        {"q":"print(5>10 or 3<7)?","code":None,"a":"False","b":"True","c":"None","d":"Error","ans":"b","exp":"False or True = True."},
        {"q":"print(not True)?","code":None,"a":"True","b":"1","c":"False","d":"None","ans":"c","exp":"not інвертує: not True = False."},
        {"q":"Скільки elif може бути в if-блоці?","code":None,"a":"Тільки 1","b":"Максимум 3","c":"Необмежено","d":"0","ans":"c","exp":"В Python необмежена кількість elif."},
        {"q":"Що виведе?","code":"x=0\nif x:\n    print('Є')\nelse:\n    print('Нема')","a":"Є","b":"Нема","c":"0","d":"Error","ans":"b","exp":"0 є falsy — умова False."},
        {"q":"Що виведе?","code":"a,b=3,5\nprint('max:',a if a>b else b)","a":"max: 3","b":"max: 5","c":"max: a","d":"Error","ans":"b","exp":"Тернарний оператор: a>b False → b=5."},
        {"q":"!= означає?","code":None,"a":"Присвоєння","b":"Не дорівнює","c":"Менше або рівне","d":"Приблизно рівне","ans":"b","exp":"!= — оператор нерівності."},
        {"q":"print(1<2<3)?","code":None,"a":"Error","b":"False","c":"True","d":"(True,True)","ans":"c","exp":"Python підтримує ланцюгові порівняння."},
        {"q":"Що виведе?","code":"x=None\nif x is None:\n    print('None!')","a":"Нічого","b":"None!","c":"Error","d":"False","ans":"b","exp":"x is None → True."},
        {"q":"Різниця == та is?","code":None,"a":"Немає різниці","b":"== порівнює значення, is — об'єкти в пам'яті","c":"is порівнює значення","d":"is тільки для None","ans":"b","exp":"== — рівність значень; is — той самий об'єкт."},
        {"q":"Як перевірити 1≤x≤10?","code":None,"a":"1<x>10","b":"x>=1 or x<=10","c":"1<=x<=10","d":"x in range(1,10)","ans":"c","exp":"Ланцюгове порівняння. range(1,10) не включає 10."},
        {"q":"print(bool([]))?","code":None,"a":"True","b":"None","c":"Error","d":"False","ans":"d","exp":"Порожній список — falsy значення."},
        {"q":"Що виведе?","code":"x='python'\nif 'py' in x:\n    print('Є!')","a":"Нічого","b":"Є!","c":"True","d":"Error","ans":"b","exp":"in перевіряє підрядок у рядку."},
        {"q":"print(5!=5)?","code":None,"a":"True","b":"None","c":"5!=5","d":"False","ans":"d","exp":"5!=5 → False."},
        {"q":"Falsy значення в Python?","code":None,"a":"0, '', [], None","b":"0, '0', False","c":"None, 0, True","d":"'', 0, [0]","ans":"a","exp":"Falsy: 0, 0.0, '', [], {}, None, False. '0' і [0] є truthy."},
        {"q":"Що виведе?","code":"if True:\n    if False:\n        print('A')\n    else:\n        print('B')\nelse:\n    print('C')","a":"A","b":"B","c":"C","d":"B і C","ans":"b","exp":"Зовнішній True, внутрішній False → внутрішній else."},
        {"q":"Що виведе?","code":"x=15\nprint('FizzBuzz' if x%15==0 else 'Fizz' if x%3==0 else 'Buzz' if x%5==0 else x)","a":"15","b":"Fizz","c":"Buzz","d":"FizzBuzz","ans":"d","exp":"15%15==0 → 'FizzBuzz'."},
    ],

    "loops": [
        {"q":"Скільки разів виведеться 'Hi'?","code":"for i in range(3):\n    print('Hi')","a":"0","b":"2","c":"3","d":"4","ans":"c","exp":"range(3) → [0,1,2] — 3 ітерації."},
        {"q":"Що виведе?","code":"for i in range(2,6):\n    print(i,end=' ')","a":"2 3 4 5","b":"2 3 4 5 6","c":"1 2 3 4 5","d":"0 1 2 3","ans":"a","exp":"range(2,6) → [2,3,4,5]."},
        {"q":"Що виведе?","code":"i=0\nwhile i<3:\n    print(i)\n    i+=1","a":"0 1 2","b":"1 2 3","c":"0 1 2 3","d":"Нескінченний","ans":"a","exp":"while i<3: 0,1,2."},
        {"q":"break виконує?","code":None,"a":"Пропускає поточну ітерацію","b":"Виходить з циклу повністю","c":"Перезапускає цикл","d":"Зупиняє програму","ans":"b","exp":"break миттєво завершує цикл."},
        {"q":"continue виконує?","code":None,"a":"Виходить з циклу","b":"Перезапускає цикл","c":"Пропускає решту поточної ітерації","d":"Нічого","ans":"c","exp":"continue пропускає залишок тіла і йде до наступної ітерації."},
        {"q":"Що виведе?","code":"for i in range(5):\n    if i==3:\n        break\n    print(i)","a":"0 1 2 3","b":"0 1 2","c":"0 1 2 3 4","d":"1 2 3","ans":"b","exp":"break при i==3. Виводяться 0,1,2."},
        {"q":"Що виведе?","code":"for i in range(5):\n    if i==2:\n        continue\n    print(i)","a":"0 1 2 3 4","b":"0 1 3 4","c":"2","d":"0 1","ans":"b","exp":"continue пропускає i==2."},
        {"q":"range(1,10,2) це?","code":None,"a":"1 до 10 з кроком 2","b":"1,3,5,7,9","c":"Обидва правильні","d":"2,4,6,8,10","ans":"c","exp":"range(start,stop,step): 1,3,5,7,9."},
        {"q":"Що виведе?","code":"for i in 'abc':\n    print(i)","a":"'abc'","b":"a b c","c":"0 1 2","d":"Error","ans":"b","exp":"for по рядку дає кожен символ."},
        {"q":"Скільки ітерацій: for i in range(0)?","code":None,"a":"1","b":"0","c":"Error","d":"Нескінченно","ans":"b","exp":"range(0) — порожня послідовність."},
        {"q":"Що виведе?","code":"x=0\nfor i in range(5):\n    x+=i\nprint(x)","a":"10","b":"15","c":"5","d":"0","ans":"a","exp":"0+1+2+3+4=10."},
        {"q":"Нескінченний цикл?","code":None,"a":"for True:","b":"loop:","c":"while True:","d":"repeat:","ans":"c","exp":"while True: — класичний нескінченний цикл."},
        {"q":"Що виведе?","code":"for i in range(3):\n    pass\nprint('done')","a":"0 1 2 done","b":"done","c":"Error","d":"Нічого","ans":"b","exp":"pass — пусте тіло. Виводить 'done'."},
        {"q":"enumerate() дає?","code":None,"a":"Тільки індекси","b":"Тільки значення","c":"Пари (індекс, значення)","d":"Словник","ans":"c","exp":"enumerate([a,b,c]) → (0,a),(1,b),(2,c)."},
        {"q":"Що виведе?","code":"for i in range(10):\n    if i%2==0:\n        continue\n    print(i,end=' ')","a":"0 2 4 6 8","b":"1 3 5 7 9","c":"0 1 2 3","d":"1 2 3 4 5","ans":"b","exp":"continue пропускає парні."},
        {"q":"list comprehension — це?","code":None,"a":"Тип помилки","b":"Стислий спосіб створити список через for","c":"Метод сортування","d":"Вбудована функція","ans":"b","exp":"[x*2 for x in range(5)] — компактний for."},
        {"q":"Що виведе?","code":"i=10\nwhile i>0:\n    i-=3\nprint(i)","a":"0","b":"1","c":"-2","d":"3","ans":"c","exp":"10→7→4→1→-2 (умова стає False)."},
        {"q":"Як отримати індекс у for?","code":None,"a":"for index,val in list:","b":"for i,val in enumerate(list):","c":"for i in range(list):","d":"list.index()","ans":"b","exp":"enumerate(list) → (індекс, значення)."},
        {"q":"Що виведе?","code":"result=[i**2 for i in range(4)]\nprint(result)","a":"[0,1,4,9]","b":"[1,4,9,16]","c":"[0,1,2,3]","d":"[4,9,16,25]","ans":"a","exp":"0²=0,1²=1,2²=4,3²=9."},
        {"q":"zip([1,2],[3,4]) дає?","code":None,"a":"[1,2,3,4]","b":"[(1,3),(2,4)]","c":"{1:3,2:4}","d":"Error","ans":"b","exp":"zip об'єднує елементи попарно."},
    ],

    "functions": [
        {"q":"Як оголосити функцію?","code":None,"a":"function greet():","b":"def greet():","c":"fun greet():","d":"func greet():","ans":"b","exp":"Ключове слово def."},
        {"q":"Що виведе?","code":"def add(a,b):\n    return a+b\nprint(add(3,4))","a":"a+b","b":"7","c":"3 4","d":"Error","ans":"b","exp":"3+4=7."},
        {"q":"Функція без return повертає?","code":None,"a":"0","b":"False","c":"None","d":"Error","ans":"c","exp":"Без return повертається None."},
        {"q":"Що виведе?","code":"def greet(name='World'):\n    print(f'Hello, {name}!')\ngreet()","a":"Hello, !","b":"Hello, name!","c":"Hello, World!","d":"Error","ans":"c","exp":"name='World' — аргумент за замовчуванням."},
        {"q":"*args — це?","code":None,"a":"Розпакування словника","b":"Довільна кількість позиційних аргументів","c":"Обов'язковий аргумент","d":"Тільки для рядків","ans":"b","exp":"*args збирає positional аргументи у tuple."},
        {"q":"**kwargs — це?","code":None,"a":"Довільна кількість іменованих аргументів","b":"Розпакування списку","c":"Тільки str ключі","d":"Обов'язковий словник","ans":"a","exp":"**kwargs збирає keyword аргументи у словник."},
        {"q":"Що виведе?","code":"def sq(x):\n    return x**2\nprint(sq(sq(2)))","a":"4","b":"8","c":"16","d":"Error","ans":"c","exp":"sq(2)=4, sq(4)=16."},
        {"q":"Рекурсія — це?","code":None,"a":"Цикл for у функції","b":"Функція що викликає саму себе","c":"Вкладені if","d":"Список у функції","ans":"b","exp":"Рекурсія — функція викликає себе. Потрібна база."},
        {"q":"Що виведе?","code":"f=lambda x: x*2\nprint(f(5))","a":"x*2","b":"10","c":"5","d":"Error","ans":"b","exp":"lambda x: x*2. f(5)=10."},
        {"q":"Чи можна передати функцію як аргумент?","code":None,"a":"Ні","b":"Тільки вбудовані","c":"Так, функції — об'єкти першого класу","d":"Тільки lambda","ans":"c","exp":"В Python функції — об'єкти. Можна передавати."},
        {"q":"Що виведе?","code":"def mul(*args):\n    r=1\n    for n in args: r*=n\n    return r\nprint(mul(2,3,4))","a":"9","b":"24","c":"Error","d":"2 3 4","ans":"b","exp":"2*3*4=24."},
        {"q":"Локальна змінна у функції?","code":None,"a":"Доступна скрізь","b":"Тільки всередині функції","c":"Зберігається між викликами","d":"Це глобальна","ans":"b","exp":"Локальні змінні існують лише під час виконання функції."},
        {"q":"Що виведе?","code":"x=10\ndef change():\n    x=20\nchange()\nprint(x)","a":"20","b":"10","c":"Error","d":"None","ans":"b","exp":"x=20 у функції — нова локальна. Глобальна x=10."},
        {"q":"global дозволяє?","code":None,"a":"Оголосити нову функцію","b":"Змінювати глобальну змінну у функції","c":"Імпортувати модуль","d":"Створити константу","ans":"b","exp":"global x дозволяє функції змінювати глобальну x."},
        {"q":"Що виведе?","code":"def outer():\n    x=1\n    def inner():\n        return x+1\n    return inner()\nprint(outer())","a":"1","b":"2","c":"Error","d":"None","ans":"b","exp":"inner() має доступ до x=1. Повертає 2."},
        {"q":"Що виведе?","code":"print(list(map(lambda x:x**2,[1,2,3])))","a":"[1,4,9]","b":"[2,4,6]","c":"[1,2,3]","d":"Error","ans":"a","exp":"map застосовує функцію: 1²=1,2²=4,3²=9."},
        {"q":"Що виведе?","code":"print(list(filter(lambda x:x>2,[1,2,3,4])))","a":"[1,2]","b":"[3,4]","c":"[2,3,4]","d":"[1,2,3,4]","ans":"b","exp":"filter залишає де умова True: 3,4."},
        {"q":"Декоратор функції — це?","code":None,"a":"Аргумент функції","b":"Функція що обгортає іншу","c":"Тип даних","d":"return","ans":"b","exp":"@decorator — wrapped = decorator(wrapped)."},
        {"q":"Що виведе?","code":"def fact(n):\n    if n==0: return 1\n    return n*fact(n-1)\nprint(fact(4))","a":"10","b":"24","c":"4","d":"Error","ans":"b","exp":"4!=4*3*2*1=24."},
        {"q":"sorted([3,1,2], key=lambda x:-x) дає?","code":None,"a":"[1,2,3]","b":"[3,2,1]","c":"[-3,-2,-1]","d":"Error","ans":"b","exp":"key=lambda x:-x сортує за спаданням."},
    ],

    "lists": [
        {"q":"Як створити порожній список?","code":None,"a":"{}","b":"[]","c":"()","d":"list{}","ans":"b","exp":"[] або list() — порожній список."},
        {"q":"Що виведе lst[1]?","code":"lst=[1,2,3]","a":"1","b":"2","c":"3","d":"Error","ans":"b","exp":"Індексація з 0. lst[1]=2."},
        {"q":"Що виведе lst[-1]?","code":"lst=[1,2,3]","a":"1","b":"2","c":"3","d":"Error","ans":"c","exp":"Від'ємний індекс: lst[-1]=останній=3."},
        {"q":"Як додати елемент в кінець?","code":None,"a":"lst.add(x)","b":"lst.insert(x)","c":"lst.append(x)","d":"lst.push(x)","ans":"c","exp":"append() додає в кінець."},
        {"q":"Що виведе lst[1:3]?","code":"lst=[1,2,3,4,5]","a":"[1,2,3]","b":"[2,3]","c":"[2,3,4]","d":"[1,3]","ans":"b","exp":"[1:3] → індекси 1,2 (3 не включається)."},
        {"q":"Як видалити за значенням?","code":None,"a":"lst.delete(x)","b":"lst.remove(x)","c":"lst.pop(x)","d":"del lst[x]","ans":"b","exp":"remove(x) видаляє перше входження x."},
        {"q":"sorted(lst) vs lst.sort()?","code":None,"a":"sorted сортує на місці","b":"sorted повертає новий список","c":"Однакові","d":"sorted тільки для чисел","ans":"b","exp":"sorted() → новий список. sort() — на місці."},
        {"q":"Що виведе len([3,1,4,1,5])?","code":None,"a":"4","b":"5","c":"14","d":"3","ans":"b","exp":"5 елементів."},
        {"q":"Що виведе?","code":"lst=[1,2,3]\nlst.extend([4,5])\nprint(lst)","a":"[1,2,3,[4,5]]","b":"[1,2,3,4,5]","c":"Error","d":"[[1,2,3],[4,5]]","ans":"b","exp":"extend() додає всі елементи."},
        {"q":"print(2 in [1,2,3])?","code":None,"a":"2","b":"False","c":"True","d":"Error","ans":"c","exp":"in перевіряє наявність: True."},
        {"q":"lst[::-1] дає?","code":None,"a":"Половину","b":"Порожній","c":"Перевернутий","d":"Error","ans":"c","exp":"[::-1] — крок -1, тобто задом наперед."},
        {"q":"Що виведе [1,2,3]*2?","code":None,"a":"6","b":"[2,4,6]","c":"[1,2,3,1,2,3]","d":"Error","ans":"c","exp":"* конкатенує список із собою."},
        {"q":"pop() без аргументу?","code":None,"a":"Видаляє перший","b":"Видаляє і повертає останній","c":"Очищає список","d":"Error","ans":"b","exp":"pop() видаляє і повертає останній елемент."},
        {"q":"Що виведе?","code":"nums=[1,2,3,4]\nresult=[x for x in nums if x%2==0]\nprint(result)","a":"[1,3]","b":"[2,4]","c":"[1,2,3,4]","d":"Error","ans":"b","exp":"list comprehension з умовою: парні."},
        {"q":"Як знайти індекс першого x?","code":None,"a":"lst.find(x)","b":"lst.search(x)","c":"lst.index(x)","d":"index(lst,x)","ans":"c","exp":"lst.index(x) повертає індекс першого входження."},
        {"q":"Що виведе?","code":"a=[1,2]\nb=a\nb.append(3)\nprint(a)","a":"[1,2]","b":"[1,2,3]","c":"Error","d":"[3]","ans":"b","exp":"b=a — той самий об'єкт. Зміна b змінює a."},
        {"q":"Як скопіювати список?","code":None,"a":"b=a","b":"b=a.copy()","c":"b=list.copy(a)","d":"b=copy(a)","ans":"b","exp":"a.copy() або a[:] — поверхнева копія."},
        {"q":"Що виведе?","code":"lst=[1,[2,3],4]\nprint(lst[1][0])","a":"2","b":"1","c":"[2,3]","d":"Error","ans":"a","exp":"lst[1]=[2,3], lst[1][0]=2."},
        {"q":"Що повертає min/max?","code":None,"a":"Суму і різницю","b":"Мінімальний і максимальний","c":"Індекси","d":"Середнє","ans":"b","exp":"min([3,1,4])=1, max([3,1,4])=4."},
        {"q":"sum(range(5))?","code":None,"a":"10","b":"15","c":"5","d":"Error","ans":"a","exp":"0+1+2+3+4=10."},
    ],

    "dicts": [
        {"q":"Як створити порожній словник?","code":None,"a":"[]","b":"()","c":"{}","d":"dict[]","ans":"c","exp":"{} або dict() — порожній словник."},
        {"q":"Що виведе d['a']?","code":"d={'a':1,'b':2}","a":"a","b":"1","c":"{'a':1}","d":"Error","ans":"b","exp":"d['a'] повертає значення 1."},
        {"q":"Неіснуючий ключ?","code":None,"a":"None","b":"0","c":"KeyError","d":"False","ans":"c","exp":"Виникає KeyError. Безпечніше: d.get('key')."},
        {"q":"d.get('key','default') повертає?","code":None,"a":"KeyError","b":"None","c":"Значення або default","d":"'key'","ans":"c","exp":"get повертає значення або default якщо ключ відсутній."},
        {"q":"Що виведе?","code":"d={'x':1}\nd['x']+=10\nprint(d['x'])","a":"1","b":"10","c":"11","d":"Error","ans":"c","exp":"1+10=11."},
        {"q":"Список ключів?","code":None,"a":"d.values()","b":"d.items()","c":"d.keys()","d":"list(d.key)","ans":"c","exp":"d.keys() — view з ключами."},
        {"q":"Пари ключ-значення?","code":None,"a":"d.pairs()","b":"d.items()","c":"d.entries()","d":"zip(d)","ans":"b","exp":"d.items() — пари (key,value)."},
        {"q":"len({'a':1,'b':2,'c':3})?","code":None,"a":"1","b":"3","c":"6","d":"abc","ans":"b","exp":"3 пари ключ-значення."},
        {"q":"Перевірити наявність ключа?","code":None,"a":"d.has('key')","b":"'key' in d","c":"d.contains('key')","d":"d.exists('key')","ans":"b","exp":"'key' in d — стандартна перевірка."},
        {"q":"Що виведе?","code":"d={}\nd.update({'a':1,'b':2})\nprint(d)","a":"{}","b":"{'a':1,'b':2}","c":"Error","d":"[('a',1),('b',2)]","ans":"b","exp":"update() додає пари."},
        {"q":"set відрізняється від list?","code":None,"a":"Без порядку, без дублікатів","b":"Тільки числа","c":"Незмінний","d":"Немає різниці","ans":"a","exp":"set — невпорядкована колекція унікальних елементів."},
        {"q":"len({1,2,2,3,3,3})?","code":None,"a":"6","b":"3","c":"1","d":"Error","ans":"b","exp":"set видаляє дублікати: {1,2,3} — 3 елементи."},
        {"q":"{1,2}|{2,3} дає?","code":None,"a":"Перетин","b":"{1,2,3}","c":"{2}","d":"Error","ans":"b","exp":"| — об'єднання: {1,2,3}."},
        {"q":"{1,2,3}&{2,3,4} дає?","code":None,"a":"{1,2,3,4}","b":"{2,3}","c":"{1,4}","d":"Error","ans":"b","exp":"& — перетин: {2,3}."},
        {"q":"Що виведе?","code":"d={'a':1,'b':2}\ndel d['a']\nprint(d)","a":"{'a':1,'b':2}","b":"{'b':2}","c":"Error","d":"{}","ans":"b","exp":"del видаляє пару 'a':1."},
        {"q":"dict comprehension виглядає як?","code":None,"a":"[k:v for k,v in items]","b":"{k:v for k,v in items}","c":"(k:v for k,v in items)","d":"dict[k:v for items]","ans":"b","exp":"{k:v for k,v in items.items()} — компактний словник."},
        {"q":"Ітерування по словнику дає?","code":"d={'name':'Alice','age':25}\nfor key in d:\n    print(key)","a":"Alice 25","b":"name age","c":"name:Alice age:25","d":"Error","ans":"b","exp":"Ітерування по словнику дає ключі."},
        {"q":"d.pop('key') виконує?","code":None,"a":"Видаляє і повертає значення","b":"Повертає перший ключ","c":"Видаляє останній","d":"Очищає","ans":"a","exp":"pop(key) видаляє і повертає значення за ключем."},
        {"q":"frozenset відрізняється від set?","code":None,"a":"Може мати дублікати","b":"Незмінний (immutable)","c":"Впорядкований","d":"Зберігає None","ans":"b","exp":"frozenset — незмінна версія set. Можна використовувати як ключ."},
        {"q":"d.get('b',0) якщо 'b' відсутній?","code":"d={'a':1}","a":"KeyError","b":"None","c":"0","d":"'b'","ans":"c","exp":"get повертає default=0 якщо ключ відсутній."},
    ],

    "strings": [
        {"q":"len('hello')?","code":None,"a":"4","b":"5","c":"6","d":"Error","ans":"b","exp":"5 символів."},
        {"q":"'hello'[1]?","code":None,"a":"h","b":"e","c":"l","d":"Error","ans":"b","exp":"[0]='h', [1]='e'."},
        {"q":"'Hello'.lower()?","code":None,"a":"HELLO","b":"hello","c":"Hello","d":"Error","ans":"b","exp":"lower() → нижній регістр."},
        {"q":"'hello world'.split()?","code":None,"a":"['hello world']","b":"['hello','world']","c":"('hello','world')","d":"Error","ans":"b","exp":"split() без аргументу розбиває по пробілах."},
        {"q":"', '.join(['a','b','c'])?","code":None,"a":"['a','b','c']","b":"a, b, c","c":"a b c","d":"Error","ans":"b","exp":"join() з'єднує рядком-роздільником."},
        {"q":"Що виведе?","code":"name='Alice'\nprint(f'Hello, {name}!')","a":"Hello, {name}!","b":"Hello, Alice!","c":"f'Hello, Alice!'","d":"Error","ans":"b","exp":"f-string підставляє значення змінної."},
        {"q":"'hello'.upper()?","code":None,"a":"hello","b":"Hello","c":"HELLO","d":"Error","ans":"c","exp":"upper() → верхній регістр."},
        {"q":"'  hello  '.strip()?","code":None,"a":"'  hello  '","b":"hello","c":"' hello '","d":"Error","ans":"b","exp":"strip() видаляє пробіли з країв."},
        {"q":"'hello'.replace('l','r')?","code":None,"a":"helro","b":"herlo","c":"herro","d":"Error","ans":"c","exp":"replace() замінює ВСІ входження: ll→rr."},
        {"q":"'hello'.startswith('he')?","code":None,"a":"he","b":"False","c":"True","d":"Error","ans":"c","exp":"startswith() → True якщо рядок починається з префіксу."},
        {"q":"Рядки в Python є?","code":None,"a":"Змінними (mutable)","b":"Незмінними (immutable)","c":"Змінними тільки через replace","d":"Списками символів","ans":"b","exp":"Рядки незмінні. Будь-яка 'зміна' створює новий рядок."},
        {"q":"'Python'[2:5]?","code":None,"a":"Pyt","b":"yth","c":"tho","d":"hon","ans":"b","exp":"Індекси 2,3,4 = 'y','t','h' → 'yth'."},
        {"q":"'hello'*3?","code":None,"a":"3","b":"hellohellohello","c":"Error","d":"['hello','hello','hello']","ans":"b","exp":"Множення рядка повторює його."},
        {"q":"'python'.find('on') → ?","code":None,"a":"True","b":"4","c":"2","d":"-1","ans":"b","exp":"'on' починається на позиції 4."},
        {"q":"str(42)?","code":None,"a":"42","b":"'42'","c":"int","d":"Error","ans":"b","exp":"str() конвертує у рядок '42'."},
        {"q":"'hello'.capitalize()?","code":None,"a":"HELLO","b":"Hello","c":"hello","d":"hELLO","ans":"b","exp":"capitalize() → перша велика, решта малі."},
        {"q":"print('py' in 'python')?","code":None,"a":"py","b":"False","c":"True","d":"Error","ans":"c","exp":"in перевіряє підрядок: True."},
        {"q":"join() vs + для конкатенації?","code":None,"a":"Немає різниці","b":"join() ефективніший для великих списків","c":"+ ефективніший","d":"join() тільки для int","ans":"b","exp":"join() виділяє пам'ять один раз, + — кожного разу."},
        {"q":"'a,b,c,d'.split(',') → len()?","code":None,"a":"3","b":"4","c":"7","d":"Error","ans":"b","exp":"['a','b','c','d'] — 4 елементи."},
        {"q":"print(f'{3.14159:.2f}')?","code":None,"a":"3.14159","b":"3.14","c":"3","d":"Error","ans":"b","exp":":.2f форматує з 2 знаками після коми."},
    ],

    "errors": [
        {"q":"Ключове слово для перехоплення винятку?","code":None,"a":"catch","b":"handle","c":"except","d":"rescue","ans":"c","exp":"Python: try/except (не catch як у Java)."},
        {"q":"Що виведе?","code":"try:\n    x=1/0\nexcept ZeroDivisionError:\n    print('Ділення на нуль!')","a":"Error","b":"Ділення на нуль!","c":"0","d":"None","ans":"b","exp":"1/0 → ZeroDivisionError — ловиться except."},
        {"q":"finally виконується?","code":None,"a":"Тільки при помилці","b":"Тільки без помилок","c":"Завжди","d":"Синонім return","ans":"c","exp":"finally — завжди: і при успіху, і при помилці."},
        {"q":"raise виконує?","code":None,"a":"Перехоплює виняток","b":"Навмисно викидає виняток","c":"Повертає None","d":"Зупиняє програму","ans":"b","exp":"raise Exception('msg') піднімає виняток."},
        {"q":"int('abc') викличе?","code":None,"a":"TypeError","b":"ValueError","c":"KeyError","d":"RuntimeError","ans":"b","exp":"ValueError — неправильний формат значення."},
        {"q":"lst[10] де len(lst)==3 викличе?","code":None,"a":"KeyError","b":"ValueError","c":"IndexError","d":"TypeError","ans":"c","exp":"IndexError — неіснуючий індекс."},
        {"q":"Що виведе?","code":"try:\n    pass\nexcept:\n    print('Error')\nelse:\n    print('OK')","a":"Error","b":"OK","c":"Error OK","d":"Нічого","ans":"b","exp":"else виконується якщо try завершився БЕЗ винятку."},
        {"q":"Exception — це?","code":None,"a":"Конкретний тип","b":"Базовий клас більшості винятків","c":"Синонім Error","d":"Тільки RuntimeError","ans":"b","exp":"Exception — базовий клас стандартних винятків."},
        {"q":"Що виведе?","code":"try:\n    x=int('42')\nexcept ValueError:\n    print('Помилка')\nprint(x)","a":"Помилка","b":"42","c":"Error","d":"None","ans":"b","exp":"int('42') успішно. Виводить 42."},
        {"q":"TypeError виникає коли?","code":None,"a":"Неправильний індекс","b":"Неправильний тип операнда","c":"Ключ не знайдено","d":"Ділення на нуль","ans":"b","exp":"TypeError: '2'+2 (str + int)."},
        {"q":"Зберегти виняток у змінну?","code":None,"a":"except Error as e:","b":"except Exception as e:","c":"except as e:","d":"catch Exception e:","ans":"b","exp":"except Exception as e: — зберігає в e."},
        {"q":"AttributeError виникає коли?","code":None,"a":"Об'єкт не має атрибута","b":"Неправильний тип","c":"Файл не знайдено","d":"Ділення на нуль","ans":"a","exp":"AttributeError: [].upppend() — метод не існує."},
        {"q":"NameError виникає коли?","code":None,"a":"Ім'я не визначено","b":"Неправильне ім'я файлу","c":"Помилка у функції","d":"Ключ не знайдено","ans":"a","exp":"print(x) де x не оголошено → NameError."},
        {"q":"Власний виняток?","code":None,"a":"class MyError(Exception): pass","b":"def MyError(Exception):","c":"raise new Exception","d":"error MyError=Exception()","ans":"a","exp":"Наслідуємо Exception: class MyError(Exception): pass"},
        {"q":"Що виведе?","code":"try:\n    x=10\nexcept:\n    print('A')\nelse:\n    print('B')\nfinally:\n    print('C')","a":"A C","b":"B C","c":"A B C","d":"C","ans":"b","exp":"try успішний → else('B'), finally завжди('C')."},
        {"q":"Як ігнорувати виняток?","code":None,"a":"except: pass","b":"ignore Exception:","c":"try: skip","d":"except None:","ans":"a","exp":"except: pass — ловить і нічого не робить."},
        {"q":"Що виведе?","code":"try:\n    raise RuntimeError('Ой!')\nfinally:\n    print('finally')","a":"finally","b":"Ой!","c":"finally потім помилка","d":"Error","ans":"c","exp":"finally виконується перед поширенням винятку."},
        {"q":"Що виведе?","code":"try:\n    d={}\n    print(d['key'])\nexcept KeyError:\n    print('Ключ')\nexcept Exception:\n    print('Інше')","a":"Інше","b":"Ключ","c":"None","d":"Error","ans":"b","exp":"KeyError ловиться першим відповідним except."},
        {"q":"try/except/else/finally порядок?","code":None,"a":"try→finally→except→else","b":"try→except→else→finally","c":"try→else→except→finally","d":"Будь-який","ans":"b","exp":"Правильний порядок: try, except, else, finally."},
        {"q":"ZeroDivisionError виникає коли?","code":None,"a":"Від'ємне число","b":"Ділення на нуль","c":"Цілочисельне переповнення","d":"Порожній список","ans":"b","exp":"1/0 → ZeroDivisionError."},
    ],

    "oop": [
        {"q":"Ключове слово для класу?","code":None,"a":"object","b":"struct","c":"class","d":"type","ans":"c","exp":"class MyClass: — оголошення класу."},
        {"q":"__init__ — це?","code":None,"a":"Деструктор","b":"Конструктор (ініціалізація)","c":"Статичний метод","d":"Властивість","ans":"b","exp":"__init__ викликається автоматично при створенні об'єкта."},
        {"q":"self — це?","code":None,"a":"Глобальна змінна","b":"Посилання на поточний об'єкт","c":"Тип даних","d":"Статичний метод","ans":"b","exp":"self — перший параметр методів екземпляра."},
        {"q":"Що виведе?","code":"class Dog:\n    def __init__(self,name):\n        self.name=name\n    def bark(self):\n        return f'{self.name}: Гав!'\nd=Dog('Рекс')\nprint(d.bark())","a":"Рекс: Гав!","b":"Гав!","c":"Dog.bark","d":"Error","ans":"a","exp":"d.bark() → 'Рекс: Гав!'"},
        {"q":"Наслідування запис?","code":None,"a":"class Child extends Parent:","b":"class Child(Parent):","c":"class Child inherits Parent:","d":"class Child: Parent","ans":"b","exp":"class Child(Parent): — синтаксис наслідування."},
        {"q":"super() у дочірньому класі?","code":None,"a":"Посилається на поточний клас","b":"Викликає метод батьківського класу","c":"Статичний метод","d":"Ігнорує батька","ans":"b","exp":"super().__init__() — конструктор батька."},
        {"q":"Атрибут класу (class attribute)?","code":None,"a":"Належить об'єкту","b":"Спільний для всіх об'єктів","c":"Завжди приватний","d":"Незмінний","ans":"b","exp":"Оголошується в тілі класу, спільний для всіх екземплярів."},
        {"q":"Поліморфізм — це?","code":None,"a":"Множинне наслідування","b":"Різні класи мають однаковий інтерфейс методу","c":"Приховування даних","d":"Статичні методи","ans":"b","exp":"Різні класи реалізують однойменний метод по-різному."},
        {"q":"Конвенція private атрибута?","code":None,"a":"private keyword","b":"Ім'я з одним підкресленням _attr","c":"Ім'я CAPS","d":"Немає приватних","ans":"b","exp":"_attr — угода 'внутрішній атрибут'."},
        {"q":"Що виведе?","code":"class Counter:\n    count=0\n    def __init__(self):\n        Counter.count+=1\nCounter()\nCounter()\nprint(Counter.count)","a":"0","b":"1","c":"2","d":"Error","ans":"c","exp":"count — атрибут класу. 2 об'єкти → count=2."},
        {"q":"@property дозволяє?","code":None,"a":"Статичний метод","b":"Виклик методу як атрибута","c":"Приватний метод","d":"Клонування","ans":"b","exp":"@property: obj.name замість obj.name()."},
        {"q":"Інкапсуляція — це?","code":None,"a":"Наслідування методів","b":"Приховування деталей реалізації","c":"Множинне наслідування","d":"Перевизначення методів","ans":"b","exp":"Приховування внутрішніх деталей, публічний інтерфейс."},
        {"q":"isinstance(obj, MyClass) перевіряє?","code":None,"a":"Чи є obj класом","b":"Чи є obj екземпляром MyClass або підкласу","c":"Рівність типів","d":"Наявність атрибута","ans":"b","exp":"isinstance() — правильна перевірка типу."},
        {"q":"__str__ метод?","code":None,"a":"Конвертує для print()","b":"Оголошує рядкові атрибути","c":"Порівнює об'єкти","d":"Копіює об'єкт","ans":"a","exp":"__str__ визначає відображення через str() та print()."},
        {"q":"Що виведе?","code":"class A:\n    def greet(self): return 'A'\nclass B(A):\n    def greet(self): return 'B'\nb=B()\nprint(b.greet())","a":"A","b":"B","c":"A B","d":"Error","ans":"b","exp":"B перевизначає greet(). b.greet() → 'B'."},
        {"q":"@staticmethod?","code":None,"a":"Приймає self","b":"Приймає cls","c":"Не приймає self або cls","d":"Тільки приватні","ans":"c","exp":"staticmethod — функція у класі без self або cls."},
        {"q":"@classmethod?","code":None,"a":"Приймає self","b":"Приймає cls як перший аргумент","c":"Без аргументів","d":"Тільки для наслідування","ans":"b","exp":"classmethod отримує клас (cls) замість екземпляра."},
        {"q":"MRO — це?","code":None,"a":"Порядок виконання методів","b":"Порядок пошуку методів при наслідуванні","c":"Список атрибутів","d":"Тип повернення","ans":"b","exp":"Method Resolution Order — пошук при множинному наслідуванні."},
        {"q":"Що виведе?","code":"class Rect:\n    def __init__(self,w,h):\n        self.w=w;self.h=h\n    def area(self): return self.w*self.h\nr=Rect(3,4)\nprint(r.area())","a":"7","b":"12","c":"34","d":"Error","ans":"b","exp":"3*4=12."},
        {"q":"Абстрактний клас у Python?","code":None,"a":"Не може мати методів","b":"ABC, не може бути instantiated напряму","c":"Синонім інтерфейсу","d":"Завжди має __init__","ans":"b","exp":"from abc import ABC, abstractmethod."},
    ],

    "modules": [
        {"q":"Як імпортувати os?","code":None,"a":"include os","b":"require os","c":"import os","d":"use os","ans":"c","exp":"import os — стандартний синтаксис."},
        {"q":"math.floor(3.9)?","code":None,"a":"4","b":"3","c":"3.9","d":"Error","ans":"b","exp":"floor() заокруглює вниз."},
        {"q":"from os import path означає?","code":None,"a":"Весь os","b":"Тільки path з os","c":"Замінює os","d":"Error","ans":"b","exp":"Імпортує конкретний об'єкт."},
        {"q":"json.dumps({'a':1}) повертає?","code":None,"a":"{'a':1}","b":"'{\"a\":1}'","c":"[('a',1)]","d":"Error","ans":"b","exp":"dumps() серіалізує у JSON-рядок."},
        {"q":"os.getcwd() виконує?","code":None,"a":"Змінює директорію","b":"Повертає поточну директорію","c":"Список файлів","d":"Видаляє файл","ans":"b","exp":"getcwd = get current working directory."},
        {"q":"random.randint(1,10) повертає?","code":None,"a":"Float між 1 і 10","b":"Int від 1 до 9","c":"Int від 1 до 10 включно","d":"List","ans":"c","exp":"randint включає обидва кінці."},
        {"q":"datetime.datetime.now() повертає?","code":None,"a":"Timestamp","b":"Рядок","c":"Об'єкт datetime","d":"int секунди","ans":"c","exp":"datetime.now() — об'єкт із поточною датою/часом."},
        {"q":"os.path.join('dir','file.txt') на Windows?","code":None,"a":"dir/file.txt","b":"dir\\\\file.txt","c":"dir-file.txt","d":"Error","ans":"b","exp":"join() використовує правильний роздільник для ОС."},
        {"q":"json.loads() виконує?","code":None,"a":"Завантажує файл","b":"Парсить JSON-рядок у Python-об'єкт","c":"Зберігає у файл","d":"Список модулів","ans":"b","exp":"loads='load string'. Парсить рядок."},
        {"q":"random.shuffle(lst) виконує?","code":None,"a":"Повертає новий список","b":"Перемішує на місці","c":"Сортує випадково","d":"Error","ans":"b","exp":"shuffle() модифікує список на місці, повертає None."},
        {"q":"math.sqrt(16)?","code":None,"a":"4","b":"4.0","c":"2","d":"Error","ans":"b","exp":"math.sqrt() завжди float: 4.0."},
        {"q":"__name__=='__main__'?","code":None,"a":"Перевіряє ім'я класу","b":"Код виконується тільки при прямому запуску","c":"Імпортує головний модуль","d":"Оголошує main()","ans":"b","exp":"При імпорті __name__=ім'я модуля. Напряму — '__main__'."},
        {"q":"os.listdir('.') повертає?","code":None,"a":"Поточний файл","b":"Список файлів і папок","c":"Шлях","d":"Розмір","ans":"b","exp":"listdir() — список вмісту директорії."},
        {"q":"math.ceil(3.1)?","code":None,"a":"3","b":"4","c":"3.1","d":"Error","ans":"b","exp":"ceil() заокруглює вгору."},
        {"q":"import os as o означає?","code":None,"a":"Приватний модуль","b":"Псевдонім для модуля","c":"Перевірка наявності","d":"Перейменовує файл","ans":"b","exp":"as дає псевдонім: o.getcwd()."},
        {"q":"datetime.timedelta для?","code":None,"a":"Порівняння","b":"Арифметика дат","c":"Форматування","d":"Часова зона","ans":"b","exp":"timedelta(days=7): now+timedelta(days=7) = через тиждень."},
        {"q":"random.choice(['a','b','c'])?","code":None,"a":"Весь список","b":"Випадковий елемент","c":"Індекс","d":"Error","ans":"b","exp":"choice() — один випадковий елемент."},
        {"q":"pip — це?","code":None,"a":"Вбудована функція","b":"Менеджер пакетів","c":"Тип даних","d":"Ключове слово","ans":"b","exp":"pip install package — встановлює бібліотеки."},
        {"q":"os.path.exists('f.txt') повертає?","code":None,"a":"Вміст","b":"True якщо існує","c":"Розмір","d":"Дату","ans":"b","exp":"exists() — перевіряє наявність файлу/папки."},
        {"q":"Що виведе?","code":"import json\nd=json.loads('{\"x\":42}')\nprint(d['x']*2)","a":"42","b":"84","c":"'42'","d":"Error","ans":"b","exp":"json.loads парсить → {'x':42}. 42*2=84."},
    ],
}
