"""
Seed дані для PyQuest: 10 локацій, 20 питань кожна, 10 задач для боса.
Запускати: python -m app.seeds.seed_db
"""
from sqlalchemy.orm import Session
from app.core.database import SessionLocal, engine, Base
import app.models  # noqa — реєструємо всі моделі
from app.models.location import Location, Question
from app.models.boss_challenge import BossChallenge
from app.models.progress import Achievement

# ============================================================
# ЛОКАЦІЇ
# ============================================================

LOCATIONS = [
    {"slug": "variables", "name": "Рівнина Початку", "order_index": 1,
     "description": "Безкраї поля, де все починається. Тут ти вперше дізнаєшся, як зберігати і використовувати дані.",
     "topic": "Змінні та типи даних (int, float, str, bool, None)",
     "boss_name": "Змінний Хаос", "boss_sprite_id": "chaos_boss", "background_id": "green_plains",
     "enemy_sprite_id": "named_ghost", "color_theme": "#7BC67E"},

    {"slug": "conditions", "name": "Ліс Умов", "order_index": 2,
     "description": "Густий ліс, де кожна стежка розгалужується. Тільки правильна умова приведе тебе до виходу.",
     "topic": "Умовні оператори (if, elif, else, and, or, not)",
     "boss_name": "Вилка Долі", "boss_sprite_id": "fork_boss", "background_id": "dark_forest",
     "enemy_sprite_id": "branch_shadow", "color_theme": "#5B9BD5"},

    {"slug": "loops", "name": "Печера Циклів", "order_index": 3,
     "description": "Темна печера, де час іде по колу. Лише той, хто знає вихід, зможе вибратися.",
     "topic": "for, while, break, continue, range",
     "boss_name": "Нескінченний Голем", "boss_sprite_id": "golem_boss", "background_id": "dark_cave",
     "enemy_sprite_id": "cycle_spirit", "color_theme": "#C0784E"},

    {"slug": "functions", "name": "Вежа Функцій", "order_index": 4,
     "description": "Стародавня вежа, де кожен поверх — це окрема функція. Піднімись на вершину!",
     "topic": "def, return, аргументи, *args, **kwargs, лямбда",
     "boss_name": "Рекурсивний Дракон", "boss_sprite_id": "dragon_boss", "background_id": "magic_tower",
     "enemy_sprite_id": "arg_elemental", "color_theme": "#9B59B6"},

    {"slug": "lists", "name": "Болото Списків", "order_index": 5,
     "description": "Болото, де в кожній калюжі ховається елемент. Знайди правильний індекс!",
     "topic": "list, методи списків, зрізи, list comprehension",
     "boss_name": "Список-Пожирач", "boss_sprite_id": "list_boss", "background_id": "swamp",
     "enemy_sprite_id": "index_slime", "color_theme": "#27AE60"},

    {"slug": "dicts", "name": "Замок Словників", "order_index": 6,
     "description": "Величний замок, де за кожними дверима — ключ і значення.",
     "topic": "dict, set, frozenset, методи словників",
     "boss_name": "Ключ-Майстер", "boss_sprite_id": "key_boss", "background_id": "castle",
     "enemy_sprite_id": "hash_ghost", "color_theme": "#E67E22"},

    {"slug": "strings", "name": "Хмарний Острів", "order_index": 7,
     "description": "Острів у хмарах, де кожне слово має магічну силу.",
     "topic": "str, методи рядків, f-strings, форматування",
     "boss_name": "Форматований Ліч", "boss_sprite_id": "lich_boss", "background_id": "cloud_island",
     "enemy_sprite_id": "char_fairy", "color_theme": "#3498DB"},

    {"slug": "errors", "name": "Темний Ліс Помилок", "order_index": 8,
     "description": "Ліс, де кожен крок може викликати виняток. Навчись їх ловити!",
     "topic": "try/except/finally/else, raise, Exception, типи помилок",
     "boss_name": "Баг-Лорд", "boss_sprite_id": "bug_boss", "background_id": "error_forest",
     "enemy_sprite_id": "exception_monster", "color_theme": "#E74C3C"},

    {"slug": "oop", "name": "Цитадель Класів", "order_index": 9,
     "description": "Могутня цитадель, де об'єкти та класи правлять усім.",
     "topic": "class, __init__, self, наслідування, поліморфізм",
     "boss_name": "Об'єктний Колос", "boss_sprite_id": "colossus_boss", "background_id": "citadel",
     "enemy_sprite_id": "instance_zombie", "color_theme": "#8E44AD"},

    {"slug": "modules", "name": "Фінальна Вежа", "order_index": 10,
     "description": "Фінальне випробування. Тут зібрані знання всього Python-світу.",
     "topic": "import, os, datetime, json, random, math",
     "boss_name": "Темний Компілятор", "boss_sprite_id": "compiler_boss", "background_id": "final_tower",
     "enemy_sprite_id": "module_guard", "color_theme": "#2C3E50"},
]

# ============================================================
# ПИТАННЯ (20 для кожної локації)
# ============================================================

QUESTIONS = {
    "variables": [
        {"q": "Яке значення матиме x після: x = 5; x = x + 3?", "code": None,
         "a": "5", "b": "3", "c": "8", "d": "15", "ans": "c",
         "exp": "x спочатку 5, потім додаємо 3 → x = 8."},
        {"q": "Який тип даних має значення True?", "code": None,
         "a": "str", "b": "int", "c": "float", "d": "bool", "ans": "d",
         "exp": "True і False — літерали типу bool (булевий тип)."},
        {"q": "Що виведе цей код?", "code": 'x = "5"\nprint(type(x))',
         "a": "<class 'int'>", "b": "<class 'float'>", "c": "<class 'str'>", "d": "<class 'char'>", "ans": "c",
         "exp": "Лапки роблять значення рядком (str), навіть якщо всередині число."},
        {"q": "Як правильно оголосити змінну з ім'ям 'my variable'?", "code": None,
         "a": "my variable = 10", "b": "my-variable = 10", "c": "my_variable = 10", "d": "myVariable! = 10", "ans": "c",
         "exp": "В Python імена змінних не можуть містити пробіли або дефіси. Конвенція — snake_case."},
        {"q": "Що таке None в Python?", "code": None,
         "a": "0", "b": "False", "c": 'Порожній рядок ""', "d": "Спеціальне значення 'нічого'", "ans": "d",
         "exp": "None — окремий тип NoneType, що означає відсутність значення."},
        {"q": "Що виведе print(10 / 3)?", "code": None,
         "a": "3", "b": "3.3333...", "c": "3.0", "d": "Error", "ans": "b",
         "exp": "/ завжди повертає float в Python 3. Для цілочисельного ділення використовуй //."},
        {"q": "Що виведе print(10 // 3)?", "code": None,
         "a": "3.333...", "b": "3.0", "c": "3", "d": "4", "ans": "c",
         "exp": "// — цілочисельне ділення, повертає тільки цілу частину."},
        {"q": "Яка з цих назв змінних є правильною в Python?", "code": None,
         "a": "2myvar", "b": "my-var", "c": "my var", "d": "my_var2", "ans": "d",
         "exp": "Змінна не може починатися з цифри, містити дефіс або пробіл."},
        {"q": "Що виведе: a, b = 5, 10; print(a, b)?", "code": None,
         "a": "5 10", "b": "(5, 10)", "c": "[5, 10]", "d": "Error", "ans": "a",
         "exp": "Python підтримує множинне присвоєння. a = 5, b = 10."},
        {"q": "Що виведе print(type(3.14))?", "code": None,
         "a": "<class 'int'>", "b": "<class 'str'>", "c": "<class 'float'>", "d": "<class 'double'>", "ans": "c",
         "exp": "3.14 — число з плаваючою комою, тип float."},
        {"q": "Що означає оператор ** в Python?", "code": None,
         "a": "Множення", "b": "Ділення", "c": "Степінь", "d": "Коментар", "ans": "c",
         "exp": "2 ** 3 = 8 (2 у степені 3)."},
        {"q": "Що виведе print(7 % 3)?", "code": None,
         "a": "2.333...", "b": "2", "c": "1", "d": "4", "ans": "c",
         "exp": "% — оператор остачі від ділення. 7 = 3*2 + 1, тому 7 % 3 = 1."},
        {"q": "Як у Python перевірити тип змінної x?", "code": None,
         "a": "x.type()", "b": "typeof(x)", "c": "type(x)", "d": "x::type", "ans": "c",
         "exp": "Вбудована функція type() повертає тип об'єкта."},
        {"q": "x = 5; y = '5'. Чи рівні вони? (x == y)", "code": None,
         "a": "True", "b": "False", "c": "Error", "d": "None", "ans": "b",
         "exp": "int 5 і str '5' — різні типи, тому == повертає False."},
        {"q": "Яка з операцій поверне тип int?", "code": None,
         "a": "10 / 2", "b": 'int("10")', "c": "float(10)", "d": "str(10)", "ans": "b",
         "exp": "int('10') конвертує рядок у ціле число."},
        {"q": "Що виведе: print(bool(0), bool(''), bool(1))?", "code": None,
         "a": "True True True", "b": "False False True", "c": "False True False", "d": "0 '' 1", "ans": "b",
         "exp": "0 і порожній рядок є 'falsy' в Python."},
        {"q": "Яке ключове слово не можна використовувати як ім'я змінної?", "code": None,
         "a": "data", "b": "my_list", "c": "if", "d": "number", "ans": "c",
         "exp": "if — зарезервоване слово Python і не може бути ім'ям змінної."},
        {"q": "Що виведе: x = 10; x += 5; print(x)?", "code": None,
         "a": "10", "b": "5", "c": "15", "d": "105", "ans": "c",
         "exp": "x += 5 еквівалентно x = x + 5, тому x = 15."},
        {"q": "Чи можна в Python присвоїти різні типи одній змінній?", "code": None,
         "a": "Ні, тип фіксується при оголошенні", "b": "Так, Python — динамічно типізована мова",
         "c": "Тільки якщо використати int()", "d": "Тільки числові типи", "ans": "b",
         "exp": "Python — динамічно типізована мова: змінна може змінювати тип."},
        {"q": "Що виведе print(10 == 10.0)?", "code": None,
         "a": "False", "b": "TypeError", "c": "True", "d": "None", "ans": "c",
         "exp": "Python порівнює значення, а не типи при ==. 10 і 10.0 рівні."},
    ],

    "conditions": [
        {"q": "Що виведе цей код?", "code": "x = 10\nif x > 5:\n    print('Більше')\nelse:\n    print('Менше')",
         "a": "Менше", "b": "Більше", "c": "Нічого", "d": "Error", "ans": "b",
         "exp": "10 > 5 є True, тому виконується гілка if."},
        {"q": "Що виведе цей код?", "code": "x = 5\nif x > 10:\n    print('A')\nelif x > 3:\n    print('B')\nelse:\n    print('C')",
         "a": "A", "b": "B", "c": "C", "d": "B і C", "ans": "b",
         "exp": "x > 10 → False; x > 3 → True, тому виконується elif."},
        {"q": "Що означає оператор and?", "code": None,
         "a": "Хоч одна умова True", "b": "Обидві умови True", "c": "Жодна умова не True", "d": "Заперечення", "ans": "b",
         "exp": "and повертає True тільки якщо ОБИДВА операнди True."},
        {"q": "Результат: print(5 > 3 and 2 < 4)?", "code": None,
         "a": "False", "b": "Error", "c": "5 > 3", "d": "True", "ans": "d",
         "exp": "5 > 3 → True, 2 < 4 → True, True and True → True."},
        {"q": "print(5 > 10 or 3 < 7) →?", "code": None,
         "a": "False", "b": "True", "c": "None", "d": "Error", "ans": "b",
         "exp": "5 > 10 → False, але 3 < 7 → True. False or True → True."},
        {"q": "print(not True)?", "code": None,
         "a": "True", "b": "1", "c": "False", "d": "None", "ans": "c",
         "exp": "not інвертує булеве значення: not True → False."},
        {"q": "Скільки гілок elif може бути в одному if-блоці?", "code": None,
         "a": "Тільки 1", "b": "Максимум 3", "c": "Необмежено", "d": "0", "ans": "c",
         "exp": "В Python можна мати будь-яку кількість elif після if."},
        {"q": "Що виведе?", "code": "x = 0\nif x:\n    print('Є')\nelse:\n    print('Нема')",
         "a": "Є", "b": "Нема", "c": "0", "d": "Error", "ans": "b",
         "exp": "0 — falsy значення, тому умова if x: → False, виконується else."},
        {"q": "Що виведе?", "code": "a, b = 3, 5\nprint('max:', a if a > b else b)",
         "a": "max: 3", "b": "max: 5", "c": "max: a", "d": "Error", "ans": "b",
         "exp": "Тернарний оператор: a > b → False, тому повертається b = 5."},
        {"q": "Оператор != означає...?", "code": None,
         "a": "Присвоєння", "b": "Не дорівнює", "c": "Менше або рівне", "d": "Приблизно рівне", "ans": "b",
         "exp": "!= — оператор нерівності. 5 != 3 → True."},
        {"q": "Що виведе?", "code": "x = 5\nif x == 5: print('П\\'ять')",
         "a": "Нічого", "b": "П'ять", "c": "Error (потрібні дужки)", "d": "if x == 5", "ans": "b",
         "exp": "Python дозволяє писати if і тіло в один рядок."},
        {"q": "print(1 < 2 < 3) →?", "code": None,
         "a": "Error", "b": "False", "c": "True", "d": "(True, True)", "ans": "c",
         "exp": "Python підтримує ланцюгові порівняння: 1 < 2 і 2 < 3 — обидва True."},
        {"q": "Що виведе?", "code": "x = None\nif x is None:\n    print('None!')",
         "a": "Нічого", "b": "None!", "c": "Error", "d": "False", "ans": "b",
         "exp": "x is None → True, тому виконується print."},
        {"q": "Різниця між == та is?", "code": None,
         "a": "Немає різниці", "b": "== порівнює значення, is — об'єкти в пам'яті",
         "c": "is порівнює значення, == — об'єкти", "d": "is тільки для None", "ans": "b",
         "exp": "== перевіряє рівність значень; is перевіряє чи це той самий об'єкт у пам'яті."},
        {"q": "Що виведе?", "code": "if True:\n    if False:\n        print('A')\n    else:\n        print('B')\nelse:\n    print('C')",
         "a": "A", "b": "B", "c": "C", "d": "B і C", "ans": "b",
         "exp": "Зовнішній if → True, внутрішній if → False, тому виконується внутрішній else."},
        {"q": "Як перевірити, чи x належить діапазону 1-10 включно?", "code": None,
         "a": "1 < x > 10", "b": "x >= 1 or x <= 10", "c": "1 <= x <= 10", "d": "x in range(1, 10)", "ans": "c",
         "exp": "1 <= x <= 10 — ланцюгове порівняння. range(1,10) не включає 10."},
        {"q": "print(bool([])) →?", "code": None,
         "a": "True", "b": "None", "c": "Error", "d": "False", "ans": "d",
         "exp": "Порожні колекції ([], {}, '', set()) — falsy значення."},
        {"q": "Falsy значення в Python (вибери правильне):", "code": None,
         "a": "0, '', [], None", "b": "0, '0', False", "c": "None, 0, True", "d": "'', 0, [0]", "ans": "a",
         "exp": "Falsy: 0, 0.0, '', [], {}, set(), None, False. '0' і [0] є truthy!"},
        {"q": "Що виведе?", "code": "x = 'python'\nif 'py' in x:\n    print('Є!')",
         "a": "Нічого", "b": "Є!", "c": "True", "d": "Error", "ans": "b",
         "exp": "Оператор in перевіряє чи є підрядок у рядку. 'py' є у 'python'."},
        {"q": "Результат: print(5 != 5)?", "code": None,
         "a": "True", "b": "None", "c": "5 != 5", "d": "False", "ans": "d",
         "exp": "5 != 5 → False (5 дорівнює 5)."},
    ],

    "loops": [
        {"q": "Скільки разів виведеться 'Hi'?", "code": "for i in range(3):\n    print('Hi')",
         "a": "0", "b": "2", "c": "3", "d": "4", "ans": "c",
         "exp": "range(3) → [0, 1, 2], тобто 3 ітерації."},
        {"q": "Що виведе?", "code": "for i in range(2, 6):\n    print(i, end=' ')",
         "a": "2 3 4 5", "b": "2 3 4 5 6", "c": "1 2 3 4 5", "d": "0 1 2 3", "ans": "a",
         "exp": "range(2, 6) → [2, 3, 4, 5]. Кінець не включається."},
        {"q": "Що виведе?", "code": "i = 0\nwhile i < 3:\n    print(i)\n    i += 1",
         "a": "0 1 2", "b": "1 2 3", "c": "0 1 2 3", "d": "Нескінченний цикл", "ans": "a",
         "exp": "Цикл виконується поки i < 3: виводить 0, 1, 2 і зупиняється."},
        {"q": "Що робить оператор break?", "code": None,
         "a": "Пропускає поточну ітерацію", "b": "Виходить з циклу повністю",
         "c": "Перезапускає цикл", "d": "Зупиняє програму", "ans": "b",
         "exp": "break миттєво завершує виконання циклу (for або while)."},
        {"q": "Що робить оператор continue?", "code": None,
         "a": "Виходить з циклу", "b": "Перезапускає цикл з початку",
         "c": "Пропускає решту коду в поточній ітерації", "d": "Нічого", "ans": "c",
         "exp": "continue пропускає залишок тіла поточної ітерації і переходить до наступної."},
        {"q": "Що виведе?", "code": "for i in range(5):\n    if i == 3:\n        break\n    print(i)",
         "a": "0 1 2 3", "b": "0 1 2", "c": "0 1 2 3 4", "d": "1 2 3", "ans": "b",
         "exp": "Коли i == 3, break завершує цикл. Виводяться 0, 1, 2."},
        {"q": "Що виведе?", "code": "for i in range(5):\n    if i == 2:\n        continue\n    print(i)",
         "a": "0 1 2 3 4", "b": "0 1 3 4", "c": "2", "d": "0 1", "ans": "b",
         "exp": "continue пропускає ітерацію коли i == 2. Виводяться 0, 1, 3, 4."},
        {"q": "Що таке range(1, 10, 2)?", "code": None,
         "a": "1 до 10 з кроком 2", "b": "1, 3, 5, 7, 9",
         "c": "Обидва варіанти правильні", "d": "2, 4, 6, 8, 10", "ans": "c",
         "exp": "range(start, stop, step) → 1, 3, 5, 7, 9 (крок 2, зупиняється до 10)."},
        {"q": "Що виведе?", "code": "for i in 'abc':\n    print(i)",
         "a": "'abc'", "b": "a b c", "c": "0 1 2", "d": "Error", "ans": "b",
         "exp": "for може ітерувати по рядку, отримуючи кожен символ окремо."},
        {"q": "Скільки ітерацій у: for i in range(0)?", "code": None,
         "a": "1", "b": "0", "c": "Error", "d": "Нескінченно", "ans": "b",
         "exp": "range(0) — порожня послідовність, цикл не виконується жодного разу."},
        {"q": "Що виведе?", "code": "x = 0\nfor i in range(5):\n    x += i\nprint(x)",
         "a": "10", "b": "15", "c": "5", "d": "0", "ans": "a",
         "exp": "0 + 1 + 2 + 3 + 4 = 10."},
        {"q": "Яке ключове слово для нескінченного циклу?", "code": None,
         "a": "for True:", "b": "loop:", "c": "while True:", "d": "repeat:", "ans": "c",
         "exp": "while True: — класичний нескінченний цикл. Виходять через break."},
        {"q": "Що виведе?", "code": "for i in range(3):\n    pass\nprint('done')",
         "a": "0 1 2 done", "b": "done", "c": "Error", "d": "Нічого", "ans": "b",
         "exp": "pass — пусте тіло. Цикл виконується 3 рази нічого не роблячи, потім виводить 'done'."},
        {"q": "enumerate() у циклі дає:", "code": None,
         "a": "Тільки індекси", "b": "Тільки значення",
         "c": "Пари (індекс, значення)", "d": "Словник", "ans": "c",
         "exp": "enumerate([a, b, c]) → (0, a), (1, b), (2, c)."},
        {"q": "Що виведе?", "code": "nums = [1, 2, 3]\nfor n in nums:\n    nums.append(n)\n    if len(nums) > 6:\n        break\nprint(len(nums))",
         "a": "3", "b": "6", "c": "7", "d": "Error", "ans": "c",
         "exp": "Починаємо з [1,2,3], додаємо 1, 2, 3, 1 → довжина 7, break. Відповідь 7."},
        {"q": "Що виведе?", "code": "for i in range(10):\n    if i % 2 == 0:\n        continue\n    print(i, end=' ')",
         "a": "0 2 4 6 8", "b": "1 3 5 7 9", "c": "0 1 2 3", "d": "1 2 3 4 5", "ans": "b",
         "exp": "continue пропускає парні числа. Виводяться непарні: 1, 3, 5, 7, 9."},
        {"q": "Що таке list comprehension?", "code": None,
         "a": "Тип помилки", "b": "Стислий спосіб створити список через for",
         "c": "Метод сортування", "d": "Вбудована функція", "ans": "b",
         "exp": "[x*2 for x in range(5)] → [0, 2, 4, 6, 8]. Компактний for у квадратних дужках."},
        {"q": "Що виведе?", "code": "i = 10\nwhile i > 0:\n    i -= 3\nprint(i)",
         "a": "0", "b": "1", "c": "-2", "d": "3", "ans": "c",
         "exp": "10 → 7 → 4 → 1 → -2 (умова i > 0 стає False). Виводить -2."},
        {"q": "Як отримати індекс у for-циклі?", "code": None,
         "a": "for index, val in list:", "b": "for i, val in enumerate(list):",
         "c": "for i in range(list):", "d": "list.index()", "ans": "b",
         "exp": "enumerate(list) повертає пари (індекс, значення)."},
        {"q": "Що виведе?", "code": "result = [i**2 for i in range(4)]\nprint(result)",
         "a": "[0, 1, 4, 9]", "b": "[1, 4, 9, 16]", "c": "[0, 1, 2, 3]", "d": "[4, 9, 16, 25]", "ans": "a",
         "exp": "range(4) → 0,1,2,3. Квадрати: 0, 1, 4, 9."},
    ],

    "functions": [
        {"q": "Як оголосити функцію в Python?", "code": None,
         "a": "function greet():", "b": "def greet():", "c": "fun greet():", "d": "func greet():", "ans": "b",
         "exp": "Ключове слово def (від 'define') використовується для оголошення функцій."},
        {"q": "Що виведе?", "code": "def add(a, b):\n    return a + b\nprint(add(3, 4))",
         "a": "a + b", "b": "7", "c": "3 4", "d": "Error", "ans": "b",
         "exp": "Функція повертає 3 + 4 = 7."},
        {"q": "Що повертає функція без явного return?", "code": None,
         "a": "0", "b": "False", "c": "None", "d": "Error", "ans": "c",
         "exp": "Функції без return (або з голим return) повертають None."},
        {"q": "Що виведе?", "code": "def greet(name='World'):\n    print(f'Hello, {name}!')\ngreet()",
         "a": "Hello, !", "b": "Hello, name!", "c": "Hello, World!", "d": "Error", "ans": "c",
         "exp": "name='World' — аргумент за замовчуванням. Якщо не передано — використовується 'World'."},
        {"q": "Що таке *args?", "code": None,
         "a": "Розпакування словника", "b": "Довільна кількість позиційних аргументів",
         "c": "Обов'язковий аргумент", "d": "Тільки для рядків", "ans": "b",
         "exp": "*args дозволяє передати будь-яку кількість позиційних аргументів як tuple."},
        {"q": "Що таке **kwargs?", "code": None,
         "a": "Довільна кількість іменованих аргументів", "b": "Розпакування списку",
         "c": "Ключові аргументи тільки str", "d": "Обов'язковий словник", "ans": "a",
         "exp": "**kwargs збирає іменовані аргументи у словник."},
        {"q": "Що виведе?", "code": "def square(x):\n    return x ** 2\nresult = square(square(2))\nprint(result)",
         "a": "4", "b": "8", "c": "16", "d": "Error", "ans": "c",
         "exp": "square(2) = 4, square(4) = 16."},
        {"q": "Що таке рекурсія?", "code": None,
         "a": "Цикл for всередині функції", "b": "Функція, що викликає саму себе",
         "c": "Вкладені if", "d": "Список всередині функції", "ans": "b",
         "exp": "Рекурсія — коли функція викликає саму себе. Потрібна база (умова зупинки)."},
        {"q": "Що виведе?", "code": "f = lambda x: x * 2\nprint(f(5))",
         "a": "x * 2", "b": "10", "c": "5", "d": "Error", "ans": "b",
         "exp": "lambda x: x * 2 — анонімна функція. f(5) = 5 * 2 = 10."},
        {"q": "Чи можна передати функцію як аргумент іншій функції?", "code": None,
         "a": "Ні", "b": "Тільки вбудовані функції",
         "c": "Так, функції є об'єктами першого класу", "d": "Тільки lambda", "ans": "c",
         "exp": "В Python функції — об'єкти. Їх можна передавати, повертати, зберігати у змінних."},
        {"q": "Що виведе?", "code": "def multiply(*args):\n    result = 1\n    for n in args:\n        result *= n\n    return result\nprint(multiply(2, 3, 4))",
         "a": "9", "b": "24", "c": "Error", "d": "2 3 4", "ans": "b",
         "exp": "multiply(2, 3, 4): result = 1 * 2 * 3 * 4 = 24."},
        {"q": "Локальна змінна у функції:", "code": None,
         "a": "Доступна скрізь", "b": "Доступна тільки всередині функції",
         "c": "Зберігається між викликами", "d": "Це глобальна змінна", "ans": "b",
         "exp": "Локальні змінні існують тільки під час виконання функції."},
        {"q": "Що виведе?", "code": "x = 10\ndef change():\n    x = 20\nchange()\nprint(x)",
         "a": "20", "b": "10", "c": "Error", "d": "None", "ans": "b",
         "exp": "x = 20 всередині change() — це нова локальна змінна. Глобальна x = 10 не змінюється."},
        {"q": "Ключове слово global:", "code": None,
         "a": "Оголошує нову функцію", "b": "Дозволяє змінювати глобальну змінну всередині функції",
         "c": "Імпортує модуль", "d": "Створює константу", "ans": "b",
         "exp": "global x дозволяє функції змінювати глобальну змінну x."},
        {"q": "Що виведе?", "code": "def outer():\n    x = 1\n    def inner():\n        return x + 1\n    return inner()\nprint(outer())",
         "a": "1", "b": "2", "c": "Error", "d": "None", "ans": "b",
         "exp": "inner() має доступ до x = 1 з outer() через замикання. Повертає 2."},
        {"q": "sorted() з key=:", "code": None,
         "a": "Визначає порядок (зростання/спадання)", "b": "Функція для обчислення ключа сортування",
         "c": "Перший елемент", "d": "Словник ключів", "ans": "b",
         "exp": "key= приймає функцію, що застосовується до кожного елемента для порівняння."},
        {"q": "Що виведе?", "code": "print(list(map(lambda x: x**2, [1, 2, 3])))",
         "a": "[1, 4, 9]", "b": "[2, 4, 6]", "c": "[1, 2, 3]", "d": "Error", "ans": "a",
         "exp": "map застосовує функцію до кожного елемента: 1²=1, 2²=4, 3²=9."},
        {"q": "Що виведе?", "code": "print(list(filter(lambda x: x > 2, [1, 2, 3, 4])))",
         "a": "[1, 2]", "b": "[3, 4]", "c": "[2, 3, 4]", "d": "[1, 2, 3, 4]", "ans": "b",
         "exp": "filter залишає тільки елементи де умова True: 3 > 2 і 4 > 2."},
        {"q": "Декоратор функції — це:", "code": None,
         "a": "Аргумент функції", "b": "Функція, що обгортає іншу функцію",
         "c": "Тип даних", "d": "Інструкція return", "ans": "b",
         "exp": "@decorator — синтаксичний цукор для wrapped = decorator(wrapped)."},
        {"q": "Що виведе?", "code": "def factorial(n):\n    if n == 0:\n        return 1\n    return n * factorial(n-1)\nprint(factorial(4))",
         "a": "10", "b": "24", "c": "4", "d": "Error", "ans": "b",
         "exp": "4! = 4 * 3 * 2 * 1 = 24. Рекурсивна функція факторіалу."},
    ],

    "lists": [
        {"q": "Як створити порожній список?", "code": None,
         "a": "{}", "b": "[]", "c": "()", "d": "list{}", "ans": "b",
         "exp": "[] або list() створюють порожній список."},
        {"q": "Що виведе?", "code": "lst = [1, 2, 3]\nprint(lst[1])",
         "a": "1", "b": "2", "c": "3", "d": "Error", "ans": "b",
         "exp": "Індексація починається з 0. lst[1] = 2."},
        {"q": "Що виведе?", "code": "lst = [1, 2, 3]\nprint(lst[-1])",
         "a": "1", "b": "2", "c": "3", "d": "Error", "ans": "c",
         "exp": "Від'ємний індекс рахує з кінця. lst[-1] = останній елемент = 3."},
        {"q": "Як додати елемент в кінець списку?", "code": None,
         "a": "lst.add(x)", "b": "lst.insert(x)", "c": "lst.append(x)", "d": "lst.push(x)", "ans": "c",
         "exp": "append() додає елемент в кінець списку."},
        {"q": "Що виведе?", "code": "lst = [1, 2, 3, 4, 5]\nprint(lst[1:3])",
         "a": "[1, 2, 3]", "b": "[2, 3]", "c": "[2, 3, 4]", "d": "[1, 3]", "ans": "b",
         "exp": "Зріз [1:3] → елементи з індексом 1 і 2 (3 не включається)."},
        {"q": "Як видалити елемент за значенням?", "code": None,
         "a": "lst.delete(x)", "b": "lst.remove(x)", "c": "lst.pop(x)", "d": "del lst[x]", "ans": "b",
         "exp": "remove(x) видаляє перше входження значення x."},
        {"q": "Що робить sorted(lst)?", "code": None,
         "a": "Сортує lst на місці", "b": "Повертає новий відсортований список",
         "c": "Те саме що lst.sort()", "d": "Повертає індекси", "ans": "b",
         "exp": "sorted() повертає новий список. lst.sort() сортує на місці (in-place)."},
        {"q": "Що виведе?", "code": "lst = [3, 1, 4, 1, 5]\nprint(len(lst))",
         "a": "4", "b": "5", "c": "14", "d": "3", "ans": "b",
         "exp": "len() повертає кількість елементів. Список має 5 елементів."},
        {"q": "Що виведе?", "code": "lst = [1, 2, 3]\nlst.extend([4, 5])\nprint(lst)",
         "a": "[1, 2, 3, [4, 5]]", "b": "[1, 2, 3, 4, 5]", "c": "Error", "d": "[[1,2,3],[4,5]]", "ans": "b",
         "exp": "extend() додає всі елементи з іншого ітерабельного об'єкта."},
        {"q": "Що виведе?", "code": "lst = [1, 2, 3]\nprint(2 in lst)",
         "a": "2", "b": "False", "c": "True", "d": "Error", "ans": "c",
         "exp": "in перевіряє чи є елемент у списку. 2 є у [1, 2, 3] → True."},
        {"q": "lst[::-1] дає:", "code": None,
         "a": "Половину списку", "b": "Порожній список",
         "c": "Перевернутий список", "d": "Error", "ans": "c",
         "exp": "[::-1] — зріз з кроком -1, тобто задом наперед."},
        {"q": "Що виведе?", "code": "lst = [1, 2, 3]\nprint(lst * 2)",
         "a": "6", "b": "[2, 4, 6]", "c": "[1, 2, 3, 1, 2, 3]", "d": "Error", "ans": "c",
         "exp": "lst * 2 конкатенує список із собою двічі."},
        {"q": "pop() без аргументу:", "code": None,
         "a": "Видаляє перший елемент", "b": "Видаляє і повертає останній елемент",
         "c": "Очищає список", "d": "Error", "ans": "b",
         "exp": "lst.pop() видаляє і повертає останній елемент (як у стеку)."},
        {"q": "Що виведе?", "code": "nums = [1, 2, 3, 4]\nresult = [x for x in nums if x % 2 == 0]\nprint(result)",
         "a": "[1, 3]", "b": "[2, 4]", "c": "[1, 2, 3, 4]", "d": "Error", "ans": "b",
         "exp": "list comprehension з умовою: вибирає тільки парні числа."},
        {"q": "Як отримати індекс першого входження x?", "code": None,
         "a": "lst.find(x)", "b": "lst.search(x)", "c": "lst.index(x)", "d": "index(lst, x)", "ans": "c",
         "exp": "lst.index(x) повертає індекс першого входження x."},
        {"q": "Що виведе?", "code": "a = [1, 2]\nb = a\nb.append(3)\nprint(a)",
         "a": "[1, 2]", "b": "[1, 2, 3]", "c": "Error", "d": "[3]", "ans": "b",
         "exp": "b = a не копіює список, а вказує на той самий об'єкт. Зміна b змінює a."},
        {"q": "Як скопіювати список?", "code": None,
         "a": "b = a", "b": "b = a.copy()", "c": "b = list.copy(a)", "d": "b = copy(a)", "ans": "b",
         "exp": "a.copy() або a[:] або list(a) створюють нову поверхневу копію."},
        {"q": "Що виведе?", "code": "lst = [1, [2, 3], 4]\nprint(lst[1][0])",
         "a": "2", "b": "1", "c": "[2, 3]", "d": "Error", "ans": "a",
         "exp": "lst[1] = [2, 3], lst[1][0] = 2."},
        {"q": "min() та max() повертають:", "code": None,
         "a": "Суму та різницю", "b": "Мінімальний та максимальний елементи",
         "c": "Індекси", "d": "Середнє", "ans": "b",
         "exp": "min([3,1,4]) = 1, max([3,1,4]) = 4."},
        {"q": "Що виведе?", "code": "lst = list(range(5))\nprint(sum(lst))",
         "a": "10", "b": "15", "c": "5", "d": "Error", "ans": "a",
         "exp": "range(5) → [0,1,2,3,4], sum = 0+1+2+3+4 = 10."},
    ],

    "dicts": [
        {"q": "Як створити порожній словник?", "code": None,
         "a": "[]", "b": "()", "c": "{}", "d": "dict[]", "ans": "c",
         "exp": "{} або dict() створюють порожній словник."},
        {"q": "Що виведе?", "code": "d = {'a': 1, 'b': 2}\nprint(d['a'])",
         "a": "a", "b": "1", "c": "{'a': 1}", "d": "Error", "ans": "b",
         "exp": "d['a'] повертає значення за ключем 'a' = 1."},
        {"q": "Що буде при зверненні до неіснуючого ключа?", "code": None,
         "a": "None", "b": "0", "c": "KeyError", "d": "False", "ans": "c",
         "exp": "Якщо ключа немає, виникає KeyError. Безпечна альтернатива: d.get('key')."},
        {"q": "Що повертає d.get('key', 'default')?", "code": None,
         "a": "KeyError", "b": "None", "c": "Значення ключа або 'default'", "d": "'key'", "ans": "c",
         "exp": "get(key, default) повертає значення якщо ключ є, інакше — default."},
        {"q": "Що виведе?", "code": "d = {'x': 1}\nd['x'] += 10\nprint(d['x'])",
         "a": "1", "b": "10", "c": "11", "d": "Error", "ans": "c",
         "exp": "d['x'] = 1, потім += 10 → d['x'] = 11."},
        {"q": "Як отримати список ключів словника?", "code": None,
         "a": "d.values()", "b": "d.items()", "c": "d.keys()", "d": "list(d.key)", "ans": "c",
         "exp": "d.keys() повертає view об'єкт з усіма ключами."},
        {"q": "Як отримати пари (ключ, значення)?", "code": None,
         "a": "d.pairs()", "b": "d.items()", "c": "d.entries()", "d": "zip(d)", "ans": "b",
         "exp": "d.items() повертає пари (key, value) для ітерування."},
        {"q": "Що виведе?", "code": "d = {'a': 1, 'b': 2, 'c': 3}\nprint(len(d))",
         "a": "1", "b": "3", "c": "6", "d": "abc", "ans": "b",
         "exp": "len(d) повертає кількість пар ключ-значення = 3."},
        {"q": "Як перевірити чи є ключ у словнику?", "code": None,
         "a": "d.has('key')", "b": "'key' in d", "c": "d.contains('key')", "d": "d.exists('key')", "ans": "b",
         "exp": "'key' in d — стандартна перевірка наявності ключа."},
        {"q": "Що виведе?", "code": "d = {}\nd.update({'a': 1, 'b': 2})\nprint(d)",
         "a": "{}", "b": "{'a': 1, 'b': 2}", "c": "Error", "d": "[('a',1),('b',2)]", "ans": "b",
         "exp": "update() додає/оновлює пари ключ-значення зі словника чи ітерабельного."},
        {"q": "Чим множина (set) відрізняється від списку?", "code": None,
         "a": "Не має порядку, немає дублікатів", "b": "Тільки числа",
         "c": "Незмінна", "d": "Немає відмінностей", "ans": "a",
         "exp": "set — невпорядкована колекція унікальних елементів."},
        {"q": "Що виведе?", "code": "s = {1, 2, 2, 3, 3, 3}\nprint(len(s))",
         "a": "6", "b": "3", "c": "1", "d": "Error", "ans": "b",
         "exp": "set автоматично видаляє дублікати. {1, 2, 3} → 3 елементи."},
        {"q": "Операція | для множин:", "code": None,
         "a": "Перетин", "b": "Різниця", "c": "Об'єднання", "d": "Симетрична різниця", "ans": "c",
         "exp": "{1,2} | {2,3} = {1,2,3}. | — об'єднання (union)."},
        {"q": "Операція & для множин:", "code": None,
         "a": "Об'єднання", "b": "Перетин", "c": "Різниця", "d": "Доповнення", "ans": "b",
         "exp": "{1,2,3} & {2,3,4} = {2,3}. & — перетин (intersection)."},
        {"q": "Що виведе?", "code": "d = {'a': 1, 'b': 2}\ndel d['a']\nprint(d)",
         "a": "{'a': 1, 'b': 2}", "b": "{'b': 2}", "c": "Error", "d": "{}", "ans": "b",
         "exp": "del d['a'] видаляє пару 'a': 1 зі словника."},
        {"q": "dict comprehension виглядає як:", "code": None,
         "a": "[k: v for k, v in items]", "b": "{k: v for k, v in items}",
         "c": "(k: v for k, v in items)", "d": "dict[k: v for items]", "ans": "b",
         "exp": "{k: v for k, v in items.items()} — компактне створення словника."},
        {"q": "Що виведе?", "code": "d = {'name': 'Alice', 'age': 25}\nfor key in d:\n    print(key)",
         "a": "Alice 25", "b": "name age", "c": "name:Alice age:25", "d": "Error", "ans": "b",
         "exp": "Ітерування по словнику видає ключі."},
        {"q": "pop() у словнику:", "code": None,
         "a": "Видаляє і повертає значення за ключем", "b": "Повертає перший ключ",
         "c": "Видаляє останній ключ", "d": "Очищає словник", "ans": "a",
         "exp": "d.pop('key') видаляє і повертає значення за ключем."},
        {"q": "frozenset на відміну від set:", "code": None,
         "a": "Може мати дублікати", "b": "Незмінний (immutable)",
         "c": "Впорядкований", "d": "Зберігає None", "ans": "b",
         "exp": "frozenset — незмінна версія set. Можна використовувати як ключ словника."},
        {"q": "Що виведе?", "code": "d = {'a': 1}\nprint(d.get('b', 0))",
         "a": "KeyError", "b": "None", "c": "0", "d": "'b'", "ans": "c",
         "exp": "Ключ 'b' відсутній, тому get повертає значення за замовчуванням 0."},
    ],

    "strings": [
        {"q": "Що виведе len('hello')?", "code": None,
         "a": "4", "b": "5", "c": "6", "d": "Error", "ans": "b",
         "exp": "len() рахує символи рядка. 'hello' має 5 символів."},
        {"q": "Що виведе 'hello'[1]?", "code": None,
         "a": "h", "b": "e", "c": "l", "d": "Error", "ans": "b",
         "exp": "Індексація рядка: [0]='h', [1]='e'."},
        {"q": "Що виведе 'Hello'.lower()?", "code": None,
         "a": "HELLO", "b": "hello", "c": "Hello", "d": "Error", "ans": "b",
         "exp": "lower() повертає рядок у нижньому регістрі."},
        {"q": "Що виведе 'hello world'.split()?", "code": None,
         "a": "['hello world']", "b": "['hello', 'world']", "c": "('hello', 'world')", "d": "Error", "ans": "b",
         "exp": "split() без аргументу розбиває по пробілах."},
        {"q": "Що виведе ', '.join(['a', 'b', 'c'])?", "code": None,
         "a": "['a', 'b', 'c']", "b": "a, b, c", "c": "a b c", "d": "Error", "ans": "b",
         "exp": "join() з'єднує елементи списку рядком-роздільником."},
        {"q": "Що виведе?", "code": "name = 'Alice'\nprint(f'Hello, {name}!')",
         "a": "Hello, {name}!", "b": "Hello, Alice!", "c": "f'Hello, Alice!'", "d": "Error", "ans": "b",
         "exp": "f-string замінює {name} на значення змінної."},
        {"q": "Що виведе 'hello'.upper()?", "code": None,
         "a": "hello", "b": "Hello", "c": "HELLO", "d": "Error", "ans": "c",
         "exp": "upper() повертає рядок у верхньому регістрі."},
        {"q": "Що виведе '  hello  '.strip()?", "code": None,
         "a": "'  hello  '", "b": "hello", "c": "' hello '", "d": "Error", "ans": "b",
         "exp": "strip() видаляє пробіли (та переноси рядка) на початку і в кінці."},
        {"q": "Що виведе 'hello'.replace('l', 'r')?", "code": None,
         "a": "helro", "b": "herlo", "c": "herro", "d": "Error", "ans": "c",
         "exp": "replace() замінює ВСІ входження. 'll' → 'rr'."},
        {"q": "Що виведе 'hello'.startswith('he')?", "code": None,
         "a": "he", "b": "False", "c": "True", "d": "Error", "ans": "c",
         "exp": "startswith() повертає True якщо рядок починається з вказаного префіксу."},
        {"q": "Рядки в Python є:", "code": None,
         "a": "Змінними (mutable)", "b": "Незмінними (immutable)",
         "c": "Змінними тільки через replace", "d": "Списками символів", "ans": "b",
         "exp": "Рядки незмінні. Будь-яка 'зміна' створює новий рядок."},
        {"q": "Що виведе?", "code": "s = 'Python'\nprint(s[2:5])",
         "a": "Pyt", "b": "yth", "c": "tho", "d": "hon", "ans": "b",
         "exp": "s[2:5] → символи з індексами 2, 3, 4 = 'y', 't', 'h' → 'yth'."},
        {"q": "Що виведе 'hello' * 3?", "code": None,
         "a": "3", "b": "hellohellohello", "c": "Error", "d": "['hello', 'hello', 'hello']", "ans": "b",
         "exp": "Множення рядка повторює його n разів."},
        {"q": "'python'.find('on') повертає:", "code": None,
         "a": "True", "b": "4", "c": "2", "d": "-1", "ans": "b",
         "exp": "find() повертає індекс першого входження. 'on' починається на позиції 4."},
        {"q": "Що виведе str(42)?", "code": None,
         "a": "42", "b": "'42'", "c": "int", "d": "Error", "ans": "b",
         "exp": "str() конвертує числове значення у рядок '42'."},
        {"q": "Що виведе 'hello'.capitalize()?", "code": None,
         "a": "HELLO", "b": "Hello", "c": "hello", "d": "hELLO", "ans": "b",
         "exp": "capitalize() робить першу літеру великою, решту — малими."},
        {"q": "Що виведе?", "code": "print('py' in 'python')",
         "a": "py", "b": "False", "c": "True", "d": "Error", "ans": "c",
         "exp": "in перевіряє чи є підрядок у рядку. 'py' є у 'python'."},
        {"q": "Різниця між ' '.join() і +?", "code": None,
         "a": "Немає різниці", "b": "join() швидший для великих списків",
         "c": "+ швидший", "d": "join() тільки для списків int", "ans": "b",
         "exp": "join() ефективніший бо виділяє пам'ять один раз, + — для кожної конкатенації."},
        {"q": "Що виведе?", "code": "s = 'a,b,c,d'\nparts = s.split(',')\nprint(len(parts))",
         "a": "3", "b": "4", "c": "7", "d": "Error", "ans": "b",
         "exp": "'a,b,c,d'.split(',') → ['a','b','c','d'], 4 елементи."},
        {"q": "Що виведе?", "code": "print(f'{3.14159:.2f}')",
         "a": "3.14159", "b": "3.14", "c": "3", "d": "Error", "ans": "b",
         "exp": ":.2f у f-string форматує float з 2 знаками після коми."},
    ],

    "errors": [
        {"q": "Яке ключове слово ловить виняток?", "code": None,
         "a": "catch", "b": "handle", "c": "except", "d": "rescue", "ans": "c",
         "exp": "Python використовує try/except (не try/catch як у Java/JavaScript)."},
        {"q": "Що виведе?", "code": "try:\n    x = 1 / 0\nexcept ZeroDivisionError:\n    print('Ділення на нуль!')",
         "a": "Error", "b": "Ділення на нуль!", "c": "0", "d": "None", "ans": "b",
         "exp": "1/0 → ZeroDivisionError, який ловить except блок."},
        {"q": "Що таке finally?", "code": None,
         "a": "Виконується тільки при помилці", "b": "Виконується тільки якщо помилок немає",
         "c": "Виконується завжди", "d": "Синонім return", "ans": "c",
         "exp": "finally виконується завжди: і при успіху, і при помилці (наприклад, для закриття файлу)."},
        {"q": "Що таке raise?", "code": None,
         "a": "Перехоплює виняток", "b": "Навмисно викидає виняток",
         "c": "Повертає None", "d": "Виходить з програми", "ans": "b",
         "exp": "raise Exception('msg') навмисно піднімає виняток."},
        {"q": "Який виняток виникне: int('abc')?", "code": None,
         "a": "TypeError", "b": "ValueError", "c": "KeyError", "d": "RuntimeError", "ans": "b",
         "exp": "ValueError — значення має неправильний формат. 'abc' не можна конвертувати в int."},
        {"q": "Який виняток виникне: lst[10] де len(lst) == 3?", "code": None,
         "a": "KeyError", "b": "ValueError", "c": "IndexError", "d": "TypeError", "ans": "c",
         "exp": "IndexError виникає при зверненні до неіснуючого індексу."},
        {"q": "Що виведе?", "code": "try:\n    pass\nexcept:\n    print('Error')\nelse:\n    print('OK')",
         "a": "Error", "b": "OK", "c": "Error OK", "d": "Нічого", "ans": "b",
         "exp": "else виконується якщо try-блок завершився БЕЗ винятку."},
        {"q": "Що таке Exception?", "code": None,
         "a": "Конкретний тип помилки", "b": "Базовий клас для більшості винятків",
         "c": "Синонім Error", "d": "Тільки для RuntimeError", "ans": "b",
         "exp": "Exception — базовий клас для стандартних винятків. except Exception ловить майже все."},
        {"q": "Що виведе?", "code": "try:\n    x = int('42')\nexcept ValueError:\n    print('Помилка')\nprint(x)",
         "a": "Помилка", "b": "42", "c": "Error", "d": "None", "ans": "b",
         "exp": "int('42') успішно → x = 42, except не виконується, print(x) виводить 42."},
        {"q": "TypeError виникає коли:", "code": None,
         "a": "Неправильний індекс", "b": "Неправильний тип операнда",
         "c": "Ключ не знайдено", "d": "Ділення на нуль", "ans": "b",
         "exp": "TypeError: '2' + 2 (не можна додати str і int)."},
        {"q": "Як зберегти виняток у змінну?", "code": None,
         "a": "except Error as e:", "b": "except Exception as e:",
         "c": "except as e:", "d": "catch Exception e:", "ans": "b",
         "exp": "except Exception as e: — ловимо виняток і зберігаємо в e."},
        {"q": "Що виведе?", "code": "def check(x):\n    if x < 0:\n        raise ValueError('Від\\'ємне!')\n    return x\ntry:\n    print(check(-1))\nexcept ValueError as e:\n    print(e)",
         "a": "-1", "b": "Від'ємне!", "c": "ValueError", "d": "Error", "ans": "b",
         "exp": "check(-1) піднімає ValueError('Від\\'ємне!'), except ловить і виводить повідомлення."},
        {"q": "AttributeError виникає коли:", "code": None,
         "a": "Об'єкт не має атрибута/методу", "b": "Неправильний тип",
         "c": "Файл не знайдено", "d": "Ділення на нуль", "ans": "a",
         "exp": "AttributeError: [].upppend() — метод 'upppend' не існує."},
        {"q": "Яка різниця між Error та Exception?", "code": None,
         "a": "Немає різниці", "b": "Exception — для програмних помилок, Error — для системних",
         "c": "Error — застарілий", "d": "Exception тільки у Python 3", "ans": "b",
         "exp": "Exception — ієрархія програмних помилок. Системні (MemoryError) — підклас BaseException."},
        {"q": "Що виведе?", "code": "try:\n    raise RuntimeError('Ой!')\nfinally:\n    print('finally')",
         "a": "finally", "b": "Ой!", "c": "finally, потім помилка", "d": "Error", "ans": "c",
         "exp": "finally виконується перед тим як виняток поширюється далі."},
        {"q": "Як ігнорувати виняток?", "code": None,
         "a": "except: pass", "b": "ignore Exception:", "c": "try: skip", "d": "except None:", "ans": "a",
         "exp": "except: pass ловить виняток і нічого не робить. Зазвичай поганий стиль."},
        {"q": "NameError виникає коли:", "code": None,
         "a": "Ім'я не визначено", "b": "Неправильне ім'я файлу",
         "c": "Помилка у функції", "d": "Ключ не знайдено", "ans": "a",
         "exp": "print(x) де x не оголошено → NameError: name 'x' is not defined."},
        {"q": "Що виведе?", "code": "try:\n    d = {}\n    print(d['key'])\nexcept KeyError:\n    print('Ключ не знайдено')\nexcept Exception:\n    print('Інша помилка')",
         "a": "Інша помилка", "b": "Ключ не знайдено", "c": "None", "d": "Error", "ans": "b",
         "exp": "d['key'] → KeyError, ловиться першим відповідним except."},
        {"q": "Власний виняток створюється через:", "code": None,
         "a": "class MyError(Exception): pass", "b": "def MyError(Exception):",
         "c": "raise new Exception", "d": "error MyError = Exception()", "ans": "a",
         "exp": "Класи-винятки наслідують Exception (або його підклас)."},
        {"q": "Що виведе?", "code": "try:\n    x = 10\nexcept:\n    print('A')\nelse:\n    print('B')\nfinally:\n    print('C')",
         "a": "A C", "b": "B C", "c": "A B C", "d": "C", "ans": "b",
         "exp": "try успішний → else виконується ('B'). finally завжди → 'C'."},
    ],

    "oop": [
        {"q": "Ключове слово для оголошення класу:", "code": None,
         "a": "object", "b": "struct", "c": "class", "d": "type", "ans": "c",
         "exp": "class MyClass: — оголошення класу в Python."},
        {"q": "Що таке __init__?", "code": None,
         "a": "Деструктор", "b": "Конструктор (метод ініціалізації)",
         "c": "Статичний метод", "d": "Властивість", "ans": "b",
         "exp": "__init__ викликається автоматично при створенні об'єкта."},
        {"q": "Що таке self?", "code": None,
         "a": "Глобальна змінна", "b": "Посилання на поточний об'єкт",
         "c": "Тип даних", "d": "Статичний метод", "ans": "b",
         "exp": "self — перший параметр методів екземпляра, посилання на поточний об'єкт."},
        {"q": "Що виведе?", "code": "class Dog:\n    def __init__(self, name):\n        self.name = name\n    def bark(self):\n        return f'{self.name} каже: Гав!'\nd = Dog('Рекс')\nprint(d.bark())",
         "a": "Рекс каже: Гав!", "b": "Гав!", "c": "Dog.bark", "d": "Error", "ans": "a",
         "exp": "d.bark() викликає метод для об'єкта d, де self.name = 'Рекс'."},
        {"q": "Як успадкувати клас Parent?", "code": None,
         "a": "class Child extends Parent:", "b": "class Child(Parent):",
         "c": "class Child inherits Parent:", "d": "class Child: Parent", "ans": "b",
         "exp": "class Child(Parent): — синтаксис наслідування в Python."},
        {"q": "super() у дочірньому класі:", "code": None,
         "a": "Посилається на поточний клас", "b": "Викликає метод батьківського класу",
         "c": "Оголошує статичний метод", "d": "Ігнорує батьківський клас", "ans": "b",
         "exp": "super().__init__() викликає конструктор батьківського класу."},
        {"q": "Атрибут класу (class attribute):", "code": None,
         "a": "Належить конкретному об'єкту", "b": "Спільний для всіх об'єктів класу",
         "c": "Приватний завжди", "d": "Не може бути змінений", "ans": "b",
         "exp": "Атрибути класу оголошуються в тілі класу (не в __init__) і спільні для всіх екземплярів."},
        {"q": "Що означає поліморфізм?", "code": None,
         "a": "Множинне наслідування", "b": "Різні класи мають один і той самий інтерфейс метода",
         "c": "Приховування даних", "d": "Статичні методи", "ans": "b",
         "exp": "Поліморфізм: різні класи реалізують однойменний метод по-різному."},
        {"q": "Приватна угода в Python (private by convention):", "code": None,
         "a": "private keyword", "b": "Ім'я з одним підкресленням _attr",
         "c": "Ім'я в CAPS", "d": "Немає приватних атрибутів", "ans": "b",
         "exp": "_attr — угода 'цей атрибут внутрішній'. __attr (два) робить name mangling."},
        {"q": "Що виведе?", "code": "class Counter:\n    count = 0\n    def __init__(self):\n        Counter.count += 1\nCounter()\nCounter()\nprint(Counter.count)",
         "a": "0", "b": "1", "c": "2", "d": "Error", "ans": "c",
         "exp": "count — атрибут класу. Кожен new Counter() збільшує його. Після 2 об'єктів → 2."},
        {"q": "@property decorator:", "code": None,
         "a": "Оголошує статичний метод", "b": "Дозволяє викликати метод як атрибут",
         "c": "Робить метод приватним", "d": "Клонує об'єкт", "ans": "b",
         "exp": "@property дозволяє писати obj.name замість obj.name()."},
        {"q": "Що таке інкапсуляція?", "code": None,
         "a": "Наслідування методів", "b": "Приховування деталей реалізації",
         "c": "Множинне успадкування", "d": "Перевизначення методів", "ans": "b",
         "exp": "Інкапсуляція — приховування внутрішніх деталей і надання публічного інтерфейсу."},
        {"q": "isinstance(obj, MyClass) перевіряє:", "code": None,
         "a": "Чи є obj класом", "b": "Чи є obj екземпляром MyClass (або підкласу)",
         "c": "Чи рівні типи", "d": "Чи є атрибут", "ans": "b",
         "exp": "isinstance() — правильний спосіб перевірити тип об'єкта."},
        {"q": "__str__ метод:", "code": None,
         "a": "Конвертує клас у рядок для print()", "b": "Оголошує рядкові атрибути",
         "c": "Порівнює об'єкти", "d": "Копіює об'єкт", "ans": "a",
         "exp": "__str__ визначає як об'єкт відображається через str() та print()."},
        {"q": "Що виведе?", "code": "class A:\n    def greet(self):\n        return 'A'\nclass B(A):\n    def greet(self):\n        return 'B'\nb = B()\nprint(b.greet())",
         "a": "A", "b": "B", "c": "A B", "d": "Error", "ans": "b",
         "exp": "B перевизначає greet(). b.greet() викликає B.greet()."},
        {"q": "@staticmethod:", "code": None,
         "a": "Приймає self як перший аргумент", "b": "Приймає cls як перший аргумент",
         "c": "Не приймає self або cls", "d": "Тільки для приватних методів", "ans": "c",
         "exp": "staticmethod — звичайна функція всередині класу, без self або cls."},
        {"q": "@classmethod:", "code": None,
         "a": "Приймає self", "b": "Приймає cls (клас) як перший аргумент",
         "c": "Не приймає аргументів", "d": "Тільки для наслідування", "ans": "b",
         "exp": "classmethod отримує клас (cls) замість екземпляра (self)."},
        {"q": "Що таке MRO (Method Resolution Order)?", "code": None,
         "a": "Порядок виконання методів", "b": "Порядок пошуку методів при наслідуванні",
         "c": "Список атрибутів", "d": "Тип повернення", "ans": "b",
         "exp": "MRO визначає порядок в якому Python шукає методи при множинному наслідуванні."},
        {"q": "Що виведе?", "code": "class Rect:\n    def __init__(self, w, h):\n        self.w = w\n        self.h = h\n    def area(self):\n        return self.w * self.h\nr = Rect(3, 4)\nprint(r.area())",
         "a": "7", "b": "12", "c": "34", "d": "Error", "ans": "b",
         "exp": "3 * 4 = 12."},
        {"q": "Абстрактний клас у Python:", "code": None,
         "a": "Не може мати методів", "b": "Визначається через ABC, не може бути instantiated напряму",
         "c": "Синонім інтерфейсу", "d": "Завжди має __init__", "ans": "b",
         "exp": "from abc import ABC, abstractmethod. Підкласи зобов'язані реалізувати @abstractmethod."},
    ],

    "modules": [
        {"q": "Як імпортувати модуль os?", "code": None,
         "a": "include os", "b": "require os", "c": "import os", "d": "use os", "ans": "c",
         "exp": "import os — стандартний синтаксис імпорту."},
        {"q": "Що виведе?", "code": "import math\nprint(math.floor(3.9))",
         "a": "4", "b": "3", "c": "3.9", "d": "Error", "ans": "b",
         "exp": "math.floor() заокруглює вниз до найближчого цілого."},
        {"q": "from os import path означає:", "code": None,
         "a": "Імпортувати весь модуль os", "b": "Імпортувати тільки path з os",
         "c": "Замінити os на path", "d": "Error", "ans": "b",
         "exp": "from module import name — імпорт конкретного об'єкта. Далі path використовується без os."},
        {"q": "import json; json.dumps({'a': 1}) повертає:", "code": None,
         "a": "{'a': 1}", "b": "'{\"a\": 1}'", "c": "[('a', 1)]", "d": "Error", "ans": "b",
         "exp": "dumps() серіалізує Python-об'єкт у JSON-рядок."},
        {"q": "Що робить os.getcwd()?", "code": None,
         "a": "Змінює директорію", "b": "Повертає поточну робочу директорію",
         "c": "Список файлів", "d": "Видаляє файл", "ans": "b",
         "exp": "getcwd = 'get current working directory'."},
        {"q": "random.randint(1, 10) повертає:", "code": None,
         "a": "Float між 1 і 10", "b": "Int від 1 до 9 включно",
         "c": "Int від 1 до 10 включно", "d": "List з 10 чисел", "ans": "c",
         "exp": "randint(a, b) — включно ОБИДВА кінці діапазону (на відміну від range)."},
        {"q": "datetime.datetime.now() повертає:", "code": None,
         "a": "Timestamp (float)", "b": "Рядок з датою",
         "c": "Об'єкт datetime з поточною датою/часом", "d": "int (секунди)", "ans": "c",
         "exp": "datetime.now() — об'єкт datetime з current local date and time."},
        {"q": "os.path.join('dir', 'file.txt') на Windows:", "code": None,
         "a": "dir/file.txt", "b": "dir\\file.txt", "c": "dir-file.txt", "d": "Error", "ans": "b",
         "exp": "os.path.join() автоматично використовує правильний роздільник для ОС."},
        {"q": "json.loads() що робить?", "code": None,
         "a": "Завантажує JSON-файл", "b": "Парсить JSON-рядок у Python-об'єкт",
         "c": "Зберігає у файл", "d": "Список усіх модулів", "ans": "b",
         "exp": "loads = 'load string'. Парсить рядок: json.loads('{\"a\":1}') → {'a': 1}."},
        {"q": "Що робить random.shuffle(lst)?", "code": None,
         "a": "Повертає новий перемішаний список", "b": "Перемішує список на місці",
         "c": "Сортує випадково", "d": "Error", "ans": "b",
         "exp": "shuffle() модифікує список на місці. Повертає None."},
        {"q": "math.sqrt(16) повертає:", "code": None,
         "a": "4", "b": "4.0", "c": "2", "d": "Error", "ans": "b",
         "exp": "math.sqrt() завжди повертає float: 4.0."},
        {"q": "Що таке __name__ == '__main__'?", "code": None,
         "a": "Перевіряє ім'я класу", "b": "Код виконується тільки якщо файл запущено напряму",
         "c": "Імпортує головний модуль", "d": "Оголошує головну функцію", "ans": "b",
         "exp": "Якщо файл імпортований, __name__ = 'module_name'. Якщо запущений напряму — '__main__'."},
        {"q": "os.listdir('.') повертає:", "code": None,
         "a": "Поточний файл", "b": "Список файлів і папок у поточній директорії",
         "c": "Шлях до файлу", "d": "Розмір директорії", "ans": "b",
         "exp": "listdir() повертає список імен файлів і папок у вказаній директорії."},
        {"q": "Що виведе?", "code": "import math\nprint(math.ceil(3.1))",
         "a": "3", "b": "4", "c": "3.1", "d": "Error", "ans": "b",
         "exp": "math.ceil() заокруглює вгору: ceil(3.1) = 4."},
        {"q": "as у import os as operating_system:", "code": None,
         "a": "Робить модуль приватним", "b": "Дає псевдонім для модуля",
         "c": "Перевіряє чи є модуль", "d": "Перейменовує файл", "ans": "b",
         "exp": "import os as o — тепер o.getcwd() замість os.getcwd()."},
        {"q": "datetime.timedelta використовується для:", "code": None,
         "a": "Порівняння дат", "b": "Арифметики з датами (різниця, додавання днів)",
         "c": "Форматування дати", "d": "Отримання часової зони", "ans": "b",
         "exp": "timedelta(days=7) — 7 днів. now + timedelta(days=7) = дата через тиждень."},
        {"q": "random.choice(['a', 'b', 'c']) повертає:", "code": None,
         "a": "Весь список", "b": "Випадковий елемент зі списку",
         "c": "Індекс", "d": "Error", "ans": "b",
         "exp": "random.choice() вибирає один випадковий елемент."},
        {"q": "Що таке pip?", "code": None,
         "a": "Вбудована функція", "b": "Менеджер пакетів Python",
         "c": "Тип даних", "d": "Ключове слово", "ans": "b",
         "exp": "pip install package — встановлює сторонні бібліотеки."},
        {"q": "os.path.exists('file.txt') повертає:", "code": None,
         "a": "Вміст файлу", "b": "True якщо файл/папка існує",
         "c": "Розмір файлу", "d": "Дату створення", "ans": "b",
         "exp": "exists() — перевіряє чи існує файл або директорія."},
        {"q": "Що виведе?", "code": "import json\nd = json.loads('{\"x\": 42}')\nprint(d['x'] * 2)",
         "a": "42", "b": "84", "c": "'42'", "d": "Error", "ans": "b",
         "exp": "json.loads парсить '{\"x\": 42}' → {'x': 42}. d['x'] = 42, * 2 = 84."},
    ],
}

# ============================================================
# БОС-ЗАДАЧІ (10 локацій)
# ============================================================

BOSS_CHALLENGES = {
    "variables": {
        "title": "Переможи Змінного Хаоса: swap_values",
        "story_text": "Змінний Хаос перемішав усі значення в країні! Лише ти можеш відновити порядок, написавши функцію обміну.",
        "task_text": "Напиши функцію swap_values(a, b), яка приймає два значення і повертає їх у зміненому порядку як tuple (b, a).\n\nПриклад:\nswap_values(3, 7) → (7, 3)\nswap_values('hello', 42) → (42, 'hello')",
        "function_signature": "def swap_values(a, b):",
        "function_call_template": "swap_values({input})",
        "starter_code": "def swap_values(a, b):\n    # твій код тут\n    pass",
        "test_cases": [
            {"input": "3, 7", "expected_output": "(7, 3)", "is_hidden": False, "description": "Базовий тест"},
            {"input": "1, 2", "expected_output": "(2, 1)", "is_hidden": False, "description": "Малі числа"},
            {"input": "'hello', 42", "expected_output": "(42, 'hello')", "is_hidden": False, "description": "Різні типи"},
            {"input": "0, 0", "expected_output": "(0, 0)", "is_hidden": True, "description": "Однакові значення"},
            {"input": "-5, 10", "expected_output": "(10, -5)", "is_hidden": True, "description": "Від'ємне число"},
        ],
        "hints": [
            {"order": 1, "text": "Функція має повернути два значення. В Python функція може повертати tuple.", "hp_cost": 10},
            {"order": 2, "text": "return b, a — це і є tuple (b, a). Python автоматично упакує у tuple.", "hp_cost": 10},
            {"order": 3, "text": "def swap_values(a, b):\n    return b, a", "hp_cost": 15},
        ],
    },

    "conditions": {
        "title": "Перехитри Вилку Долі: fizzbuzz",
        "story_text": "Вилка Долі вимагає пройти через ліс умов! Вона задає числа, а ти маєш відповідати 'Fizz', 'Buzz' або 'FizzBuzz'.",
        "task_text": "Напиши функцію fizzbuzz(n), яка повертає:\n- 'FizzBuzz' якщо n ділиться на 3 і 5\n- 'Fizz' якщо n ділиться на 3\n- 'Buzz' якщо n ділиться на 5\n- str(n) в інших випадках\n\nПриклад:\nfizzbuzz(15) → 'FizzBuzz'\nfizzbuzz(3) → 'Fizz'",
        "function_signature": "def fizzbuzz(n):",
        "function_call_template": "fizzbuzz({input})",
        "starter_code": "def fizzbuzz(n):\n    # твій код тут\n    pass",
        "test_cases": [
            {"input": "15", "expected_output": "FizzBuzz", "is_hidden": False, "description": "Ділиться на 3 і 5"},
            {"input": "3", "expected_output": "Fizz", "is_hidden": False, "description": "Ділиться на 3"},
            {"input": "5", "expected_output": "Buzz", "is_hidden": False, "description": "Ділиться на 5"},
            {"input": "7", "expected_output": "7", "is_hidden": True, "description": "Не ділиться"},
            {"input": "30", "expected_output": "FizzBuzz", "is_hidden": True, "description": "Інший кратний 15"},
        ],
        "hints": [
            {"order": 1, "text": "Спочатку перевір умову для FizzBuzz (ділиться і на 3, і на 5). Ця перевірка має бути ПЕРШОЮ.", "hp_cost": 10},
            {"order": 2, "text": "Використовуй оператор % (остача від ділення). n % 3 == 0 означає 'ділиться на 3'.", "hp_cost": 10},
            {"order": 3, "text": "if n % 15 == 0: return 'FizzBuzz'\nelif n % 3 == 0: return 'Fizz'\nelif n % 5 == 0: return 'Buzz'\nelse: return str(n)", "hp_cost": 15},
        ],
    },

    "loops": {
        "title": "Зупини Нескінченного Голема: sum_of_evens",
        "story_text": "Голем рахує нескінченно! Зупини його, порахувавши суму парних чисел від 1 до n.",
        "task_text": "Напиши функцію sum_of_evens(n), яка повертає суму всіх парних чисел від 1 до n включно.\n\nПриклад:\nsum_of_evens(10) → 30  (2+4+6+8+10)\nsum_of_evens(5) → 6   (2+4)",
        "function_signature": "def sum_of_evens(n):",
        "function_call_template": "sum_of_evens({input})",
        "starter_code": "def sum_of_evens(n):\n    # твій код тут\n    pass",
        "test_cases": [
            {"input": "10", "expected_output": "30", "is_hidden": False, "description": "Базовий тест"},
            {"input": "5", "expected_output": "6", "is_hidden": False, "description": "Непарний n"},
            {"input": "1", "expected_output": "0", "is_hidden": False, "description": "n=1, немає парних"},
            {"input": "100", "expected_output": "2550", "is_hidden": True, "description": "Великий n"},
            {"input": "2", "expected_output": "2", "is_hidden": True, "description": "n=2"},
        ],
        "hints": [
            {"order": 1, "text": "Використовуй цикл for з range(). Перевіряй кожне число чи воно парне.", "hp_cost": 10},
            {"order": 2, "text": "Парне число: n % 2 == 0. Або використай range(2, n+1, 2) щоб одразу ітерувати по парних.", "hp_cost": 10},
            {"order": 3, "text": "total = 0\nfor i in range(2, n+1, 2):\n    total += i\nreturn total", "hp_cost": 15},
        ],
    },

    "functions": {
        "title": "Розбери Рекурсивного Дракона: fibonacci",
        "story_text": "Дракон сховався за послідовністю Фібоначчі! Напиши функцію і відкрий його логово.",
        "task_text": "Напиши функцію fibonacci(n), яка повертає n-й елемент послідовності Фібоначчі (починаючи з 0).\n\nПослідовність: 0, 1, 1, 2, 3, 5, 8, 13, 21...\nfibonacci(0) → 0\nfibonacci(1) → 1\nfibonacci(7) → 13",
        "function_signature": "def fibonacci(n):",
        "function_call_template": "fibonacci({input})",
        "starter_code": "def fibonacci(n):\n    # твій код тут\n    pass",
        "test_cases": [
            {"input": "0", "expected_output": "0", "is_hidden": False, "description": "Перший елемент"},
            {"input": "1", "expected_output": "1", "is_hidden": False, "description": "Другий елемент"},
            {"input": "7", "expected_output": "13", "is_hidden": False, "description": "8-й елемент"},
            {"input": "10", "expected_output": "55", "is_hidden": True, "description": "11-й елемент"},
            {"input": "15", "expected_output": "610", "is_hidden": True, "description": "Великий n"},
        ],
        "hints": [
            {"order": 1, "text": "Базові випадки: fibonacci(0) = 0, fibonacci(1) = 1. Для n > 1: fib(n) = fib(n-1) + fib(n-2).", "hp_cost": 10},
            {"order": 2, "text": "Можна використати рекурсію або ітеративний підхід (з двома змінними a, b).", "hp_cost": 10},
            {"order": 3, "text": "a, b = 0, 1\nfor _ in range(n):\n    a, b = b, a + b\nreturn a", "hp_cost": 15},
        ],
    },

    "lists": {
        "title": "Знищ Список-Пожирача: find_second_max",
        "story_text": "Пожирач заковтнув найбільший елемент! Знайди другий за величиною.",
        "task_text": "Напиши функцію find_second_max(lst), яка повертає другий за величиною унікальний елемент списку.\n\nПриклад:\nfind_second_max([3, 1, 4, 1, 5, 9, 2, 6]) → 6\nfind_second_max([1, 2]) → 1",
        "function_signature": "def find_second_max(lst):",
        "function_call_template": "find_second_max({input})",
        "starter_code": "def find_second_max(lst):\n    # твій код тут\n    pass",
        "test_cases": [
            {"input": "[3, 1, 4, 1, 5, 9, 2, 6]", "expected_output": "6", "is_hidden": False, "description": "З дублікатами"},
            {"input": "[1, 2]", "expected_output": "1", "is_hidden": False, "description": "Два елементи"},
            {"input": "[5, 5, 5, 3]", "expected_output": "3", "is_hidden": False, "description": "Багато однакових"},
            {"input": "[10, 9, 8, 7]", "expected_output": "9", "is_hidden": True, "description": "Спадний порядок"},
            {"input": "[1, 100, 50, 100]", "expected_output": "50", "is_hidden": True, "description": "Дублікат максимума"},
        ],
        "hints": [
            {"order": 1, "text": "Спочатку видали дублікати (set), потім відсортуй. Другий з кінця — це що шукаємо.", "hp_cost": 10},
            {"order": 2, "text": "sorted(set(lst)) дає відсортований список унікальних. Індекс -2 — передостанній.", "hp_cost": 10},
            {"order": 3, "text": "unique = sorted(set(lst))\nreturn unique[-2]", "hp_cost": 15},
        ],
    },

    "dicts": {
        "title": "Розкрий Ключ-Майстра: word_count",
        "story_text": "Майстер заховався у словнику слів! Порахуй кожне слово щоб його знайти.",
        "task_text": "Напиши функцію word_count(text), яка приймає рядок і повертає словник де ключ — слово (в нижньому регістрі), значення — кількість входжень.\n\nПриклад:\nword_count('hello world hello') → {'hello': 2, 'world': 1}",
        "function_signature": "def word_count(text):",
        "function_call_template": "word_count({input})",
        "starter_code": "def word_count(text):\n    # твій код тут\n    pass",
        "test_cases": [
            {"input": "'hello world hello'", "expected_output": "{'hello': 2, 'world': 1}", "is_hidden": False, "description": "Базовий тест"},
            {"input": "'a b c a b a'", "expected_output": "{'a': 3, 'b': 2, 'c': 1}", "is_hidden": False, "description": "Три різних слова"},
            {"input": "'Hello hello HELLO'", "expected_output": "{'hello': 3}", "is_hidden": False, "description": "Різний регістр"},
            {"input": "'one'", "expected_output": "{'one': 1}", "is_hidden": True, "description": "Одне слово"},
            {"input": "'cat dog cat fish dog cat'", "expected_output": "{'cat': 3, 'dog': 2, 'fish': 1}", "is_hidden": True, "description": "Більше слів"},
        ],
        "hints": [
            {"order": 1, "text": "Розбий текст на слова через split(). Приведи до нижнього регістру через lower().", "hp_cost": 10},
            {"order": 2, "text": "Ітеруй по словах. Для кожного слова: counts[word] = counts.get(word, 0) + 1", "hp_cost": 10},
            {"order": 3, "text": "counts = {}\nfor word in text.lower().split():\n    counts[word] = counts.get(word, 0) + 1\nreturn counts", "hp_cost": 15},
        ],
    },

    "strings": {
        "title": "Зруйнуй Форматованого Ліча: is_palindrome",
        "story_text": "Ліч захований у паліндромі! Виявши його читаючи своє ім'я задом наперед.",
        "task_text": "Напиши функцію is_palindrome(s), яка повертає True якщо рядок є паліндромом (читається однаково з обох боків), False — інакше. Ігноруй регістр та пробіли.\n\nПриклад:\nis_palindrome('racecar') → True\nis_palindrome('A man a plan a canal Panama') → True\nis_palindrome('hello') → False",
        "function_signature": "def is_palindrome(s):",
        "function_call_template": "is_palindrome({input})",
        "starter_code": "def is_palindrome(s):\n    # твій код тут\n    pass",
        "test_cases": [
            {"input": "'racecar'", "expected_output": "True", "is_hidden": False, "description": "Простий паліндром"},
            {"input": "'hello'", "expected_output": "False", "is_hidden": False, "description": "Не паліндром"},
            {"input": "'A man a plan a canal Panama'", "expected_output": "True", "is_hidden": False, "description": "З пробілами і регістром"},
            {"input": "'level'", "expected_output": "True", "is_hidden": True, "description": "Ще один паліндром"},
            {"input": "'Python'", "expected_output": "False", "is_hidden": True, "description": "Не паліндром 2"},
        ],
        "hints": [
            {"order": 1, "text": "Видали пробіли (replace або split+join) і приведи до нижнього регістру.", "hp_cost": 10},
            {"order": 2, "text": "Порівняй рядок із його зворотом: s == s[::-1]", "hp_cost": 10},
            {"order": 3, "text": "cleaned = s.lower().replace(' ', '')\nreturn cleaned == cleaned[::-1]", "hp_cost": 15},
        ],
    },

    "errors": {
        "title": "Переможи Баг-Лорда: safe_divide",
        "story_text": "Баг-Лорд кидає помилки на кожному кроці! Напиши захищену функцію ділення.",
        "task_text": "Напиши функцію safe_divide(a, b), яка:\n- Повертає результат a / b (float)\n- Повертає None якщо b == 0\n- Повертає None якщо a або b не є числом (int або float)\n\nПриклад:\nsafe_divide(10, 2) → 5.0\nsafe_divide(10, 0) → None\nsafe_divide('a', 2) → None",
        "function_signature": "def safe_divide(a, b):",
        "function_call_template": "safe_divide({input})",
        "starter_code": "def safe_divide(a, b):\n    # твій код тут\n    pass",
        "test_cases": [
            {"input": "10, 2", "expected_output": "5.0", "is_hidden": False, "description": "Нормальне ділення"},
            {"input": "10, 0", "expected_output": "None", "is_hidden": False, "description": "Ділення на нуль"},
            {"input": "'a', 2", "expected_output": "None", "is_hidden": False, "description": "Не число"},
            {"input": "7, 2", "expected_output": "3.5", "is_hidden": True, "description": "Float результат"},
            {"input": "0, 5", "expected_output": "0.0", "is_hidden": True, "description": "Нуль в чисельнику"},
        ],
        "hints": [
            {"order": 1, "text": "Спочатку перевір типи: isinstance(a, (int, float)). Потім перевір b == 0.", "hp_cost": 10},
            {"order": 2, "text": "Використовуй try/except щоб ловити TypeError або ZeroDivisionError.", "hp_cost": 10},
            {"order": 3, "text": "try:\n    if not isinstance(a,(int,float)) or not isinstance(b,(int,float)):\n        return None\n    if b == 0:\n        return None\n    return float(a / b)\nexcept:\n    return None", "hp_cost": 15},
        ],
    },

    "oop": {
        "title": "Повали Об'єктного Колоса: BankAccount",
        "story_text": "Колос контролює всі рахунки! Створи власний клас BankAccount щоб перехопити контроль.",
        "task_text": "Напиши клас BankAccount з:\n- __init__(self, owner, balance=0)\n- deposit(self, amount) — додає amount до балансу, повертає новий баланс\n- withdraw(self, amount) — знімає amount якщо достатньо коштів, повертає True; якщо ні — повертає False\n- get_balance(self) — повертає поточний баланс\n\ntest: acc = BankAccount('Alice', 100); acc.deposit(50); acc.withdraw(30); acc.get_balance()",
        "function_signature": "class BankAccount:",
        "function_call_template": "BankAccount({input})",
        "starter_code": "class BankAccount:\n    def __init__(self, owner, balance=0):\n        # твій код тут\n        pass\n    \n    def deposit(self, amount):\n        pass\n    \n    def withdraw(self, amount):\n        pass\n    \n    def get_balance(self):\n        pass",
        "test_cases": [
            {"input": "'Alice', 100", "expected_output": "100",
             "is_hidden": False, "description": "Початковий баланс",
             },
            {"input": "'Bob'", "expected_output": "0",
             "is_hidden": False, "description": "Баланс за замовчуванням"},
            {"input": "'Test', 50", "expected_output": "150",
             "is_hidden": False, "description": "Після deposit(100)"},
            {"input": "'User', 100", "expected_output": "True",
             "is_hidden": True, "description": "withdraw(50) повертає True"},
            {"input": "'User', 10", "expected_output": "False",
             "is_hidden": True, "description": "withdraw(50) повертає False (недостатньо)"},
        ],
        "hints": [
            {"order": 1, "text": "В __init__ збережи owner і balance як self.owner і self.balance.", "hp_cost": 10},
            {"order": 2, "text": "deposit: self.balance += amount, return self.balance.\nwithdraw: if self.balance >= amount: self.balance -= amount; return True. Else: return False.", "hp_cost": 10},
            {"order": 3, "text": "class BankAccount:\n  def __init__(self, owner, balance=0):\n    self.owner = owner\n    self.balance = balance\n  def deposit(self, amount):\n    self.balance += amount\n    return self.balance\n  def withdraw(self, amount):\n    if self.balance >= amount:\n      self.balance -= amount\n      return True\n    return False\n  def get_balance(self):\n    return self.balance", "hp_cost": 15},
        ],
    },

    "modules": {
        "title": "Знищ Темного Компілятора: days_until",
        "story_text": "Компілятор рахує дні до кінця світу! Порахуй скільки днів залишилось до заданої дати.",
        "task_text": "Напиши функцію days_until(date_str), яка приймає рядок дати у форматі 'YYYY-MM-DD' і повертає кількість днів від сьогодні до цієї дати (ціле число). Якщо дата в минулому — від'ємне число.\n\nВикористовуй модуль datetime.\ndatetime.date.today() — сьогоднішня дата\ndatetime.datetime.strptime(date_str, '%Y-%m-%d').date() — парсинг рядка",
        "function_signature": "def days_until(date_str):",
        "function_call_template": "days_until({input})",
        "starter_code": "import datetime\n\ndef days_until(date_str):\n    # твій код тут\n    pass",
        "test_cases": [
            {"input": "'2026-12-31'", "expected_output": "220", "is_hidden": False, "description": "Кінець 2026"},
            {"input": "'2026-05-25'", "expected_output": "0", "is_hidden": False, "description": "Сьогодні"},
            {"input": "'2027-01-01'", "expected_output": "221", "is_hidden": True, "description": "Початок 2027"},
            {"input": "'2026-06-01'", "expected_output": "7", "is_hidden": True, "description": "Через тиждень"},
            {"input": "'2026-05-18'", "expected_output": "-7", "is_hidden": True, "description": "Тиждень тому"},
        ],
        "hints": [
            {"order": 1, "text": "Парс рядок: target = datetime.datetime.strptime(date_str, '%Y-%m-%d').date()", "hp_cost": 10},
            {"order": 2, "text": "today = datetime.date.today(). Різниця: (target - today).days", "hp_cost": 10},
            {"order": 3, "text": "import datetime\ndef days_until(date_str):\n    target = datetime.datetime.strptime(date_str, '%Y-%m-%d').date()\n    today = datetime.date.today()\n    return (target - today).days", "hp_cost": 15},
        ],
    },
}

# ============================================================
# АЧІВМЕНТИ
# ============================================================

ACHIEVEMENTS = [
    {"slug": "first_blood", "name": "Перший Крип", "description": "Дай першу правильну відповідь", "icon_id": "sword", "xp_reward": 10},
    {"slug": "no_death_1", "name": "Безсмертний", "description": "Пройди локацію без смертей", "icon_id": "shield", "xp_reward": 25},
    {"slug": "boss_slayer", "name": "Переможець Босів", "description": "Вбий першого боса", "icon_id": "skull", "xp_reward": 50},
    {"slug": "all_bosses", "name": "Кілер Босів", "description": "Вбий всіх 10 босів", "icon_id": "crown", "xp_reward": 200},
    {"slug": "perfectionist", "name": "Перфекціоніст", "description": "10/10 у квізі без помилок", "icon_id": "star", "xp_reward": 30},
    {"slug": "first_try", "name": "З Першої Спроби", "description": "Вбий боса з першої спроби", "icon_id": "lightning", "xp_reward": 50},
    {"slug": "no_hints", "name": "Без Підказок", "description": "Вбий боса без підказок", "icon_id": "brain", "xp_reward": 30},
    {"slug": "streak_7", "name": "Тижневий Герой", "description": "Стрік 7 днів", "icon_id": "fire", "xp_reward": 100},
    {"slug": "completionist", "name": "Завершувач", "description": "Пройди всі 10 локацій", "icon_id": "trophy", "xp_reward": 300},
    {"slug": "level_10", "name": "Досвідчений", "description": "Досягни 10 рівня", "icon_id": "gem", "xp_reward": 50},
    {"slug": "level_20", "name": "Ветеран", "description": "Досягни 20 рівня", "icon_id": "diamond", "xp_reward": 100},
]


def seed(db: Session):
    print("🌱 Починаємо seed...")

    # Achievements
    for ach_data in ACHIEVEMENTS:
        if not db.query(Achievement).filter(Achievement.slug == ach_data["slug"]).first():
            db.add(Achievement(**ach_data))
    db.commit()
    print(f"  ✅ {len(ACHIEVEMENTS)} ачівментів")

    # Locations + Questions + Boss Challenges
    for loc_data in LOCATIONS:
        loc = db.query(Location).filter(Location.slug == loc_data["slug"]).first()
        if not loc:
            loc = Location(**loc_data)
            db.add(loc)
            db.commit()
            db.refresh(loc)
            print(f"  📍 Локація: {loc.name}")

        # Questions
        existing_q = db.query(Question).filter(Question.location_id == loc.id).count()
        if existing_q == 0:
            for q in QUESTIONS.get(loc.slug, []):
                db.add(Question(
                    location_id=loc.id,
                    question_text=q["q"],
                    code_snippet=q.get("code"),
                    option_a=q["a"], option_b=q["b"],
                    option_c=q["c"], option_d=q["d"],
                    correct_option=q["ans"],
                    explanation=q["exp"],
                ))
            db.commit()
            print(f"    ❓ {len(QUESTIONS.get(loc.slug, []))} питань")

        # Boss challenge
        existing_boss = db.query(BossChallenge).filter(BossChallenge.location_id == loc.id).first()
        if not existing_boss and loc.slug in BOSS_CHALLENGES:
            bd = BOSS_CHALLENGES[loc.slug]
            db.add(BossChallenge(
                location_id=loc.id,
                title=bd["title"],
                story_text=bd["story_text"],
                task_text=bd["task_text"],
                function_signature=bd["function_signature"],
                function_call_template=bd["function_call_template"],
                starter_code=bd["starter_code"],
                test_cases=bd["test_cases"],
                hints=bd["hints"],
            ))
            db.commit()
            print(f"    👹 Бос: {bd['title'][:40]}...")

    print("✅ Seed завершено!")


if __name__ == "__main__":
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        seed(db)
    finally:
        db.close()
